(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var p0=function(a){a.X("cardstatechange",a.Rh()&&a.Tl()?1:0)},q0=function(a,b){var c=g.Na(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},RUa=function(a){var b=g.jl(a);
a=g.ml(a);return new g.Zk(b.x,b.y,a.width,a.height)},SUa=function(a){return Math.pow(a,3)},TUa=function(a){return 3*a*a-2*a*a*a},t0=function(a){a=g.Qa(a);
delete r0[a];g.Xe(r0)&&s0&&s0.stop()},VUa=function(){s0||(s0=new g.K(function(){UUa()},20));
var a=s0;a.isActive()||a.start()},UUa=function(){var a=g.Ta();
g.Me(r0,function(b){WUa(b,a)});
g.Xe(r0)||VUa()},u0=function(a,b,c,d){g.so.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.N=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},WUa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;XUa(a,a.progress);1==a.progress?(a.j=0,t0(a),a.onFinish(),a.Yy()):a.Lc()&&a.NE()},XUa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.N[c]-a.u[c])*b+a.u[c]},YUa=function(a,b){g.Ge.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},v0=function(a,b,c,d,e){u0.call(this,b,c,d,e);
this.element=a},w0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
v0.call(this,a,b,c,d,e)},x0=function(a){g.G.call(this);
this.u=a||window;this.j=[]},y0=function(a){return a.baseUrl||null},z0=function(a,b){return g.fm(g.kk(a,b),function(c){return!!c})},ZUa=function(a,b,c){function d(Aa){var Ia=Aa.hovercardButton;
if(!Ia)return null;Ia=Ia.subscribeButtonRenderer;if(!Ia)return null;var fb=f(Ia.unsubscribedButtonText),Eb=f(Ia.subscribedButtonText);if(Ia.subscribed){var Hc=f(Ia.subscriberCountWithUnsubscribeText);var Ab=f(Ia.subscriberCountText)}else Hc=f(Ia.subscriberCountText),Ab=f(Ia.subscriberCountWithSubscribeText);var Yc=null;if(Aa.signinEndpoint){Yc=q0(Aa,"signinEndpoint","webNavigationEndpointData","url");if(!Yc){var gb,Pb,yd;Yc=null==(gb=Ia.signInEndpoint)?void 0:null==(Pb=gb.commandMetadata)?void 0:
null==(yd=Pb.webCommandMetadata)?void 0:yd.url}if(!Yc)return null}return fb&&(Eb||Yc)?{subscribed:Ia.subscribed,subscribeText:fb,subscribeCount:Hc,unsubscribeText:Eb,unsubscribeCount:Ab,enabled:Ia.enabled,signinUrl:Yc,classic:Aa.useClassicSubscribeButton}:null}
function e(Aa){if(Aa){var Ia=[],fb=Aa.videoId;fb&&Ia.push("v="+fb);(fb=Aa.playlistId)&&Ia.push("list="+fb);(Aa=Aa.startTimeSeconds)&&Ia.push("t="+Aa);return"/watch?"+Ia.join("&")}}
function f(Aa){if(!Aa)return null;var Ia=Aa.simpleText;return Ia?Ia:Aa.runs?g.kk(Aa.runs,function(fb){return fb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,u=null,x=null,y=!1,z=null,D=null,H=null,J=null,L=null,ba=null;if("VIDEO"===k)l.urlEndpoint?m=l.urlEndpoint.url:(ba=l.watchEndpoint,m=e(ba)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===k)l.urlEndpoint?m=l.urlEndpoint.url:(ba=l.watchEndpoint,m=e(ba)),n=!1,q=a,u=f(b.playlistLength);
else if("CHANNEL"===k){if(y=q0(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;q="new";(y=!!b.isSubscribe)?z=d(b):D=f(b.subscribersText)}else"WEBSITE"===k?((H=q0(l,"urlEndpoint","url"))&&(m=H),n=!0,q="new",H=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===k&&(b.productPrice&&(J=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=q0(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=q0(b,"title","accessibility","accessibilityData","label");var M=b.endpoint?b.endpoint.clickTrackingParams:
null,ta="";if(b.metadata){var Y=f(b.metadata);Y&&(ta=Y)}return{id:"element-"+c,type:k,title:f(b.title),metadata:ta,callToAction:f(b.callToAction),nN:b.image,iconUrl:H,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:u,channelId:x,subscribeButton:z,subscribersText:D,isSubscribe:y,targetUrl:m||null,vX:n,sessionData:M?{itct:M}:null,g1:q,ix:a?
a:null,isPlaceholder:b.isPlaceholder,impressionUrls:z0(b.impressionUrls||[],y0),kX:z0(b.hovercardShowUrls||[],y0),clickUrls:z0(l.loggingUrls||[],y0),visualElement:g.Hu(b.trackingParams),productPrice:J,additionalFeesText:L,watchEndpoint:ba||null}},A0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:z0(a.impressionUrls||[],y0),elements:z0(a.elements||[],function(d,e){return ZUa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Hu(a.trackingParams));return c},B0=function(a){g.YI.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.V=!0;this.I=0;a=a.S();this.N=g.gB(a)||g.kB(a);this.W=a.experiments.gb("web_rounded_thumbnails");this.events=new g.mz(this);g.I(this,this.events);this.events.P(this.player,g.Fv("creatorendscreen"),this.onCueRangeEnter);this.events.P(this.player,g.Gv("creatorendscreen"),this.onCueRangeExit);this.events.P(this.player,"resize",this.wb);this.events.P(window,"focus",this.d0);this.load();var b=g.Gg("STYLE");(g.yg("HEAD")[0]||
document.body).appendChild(b);g.Fe(this,function(){g.Kg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},$Ua=function(a){return a.player.getVideoData().D?"current":a.N?"new":"current"},C0=function(a){return"creator-endscreen-editor"===a.player.S().playerStyle},aVa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=A0(f,$Ua(a))));D0(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.Ur;d&&(c.postParams={ad_tracking:d});if(b=g.Hxa(b))if(b=g.Mf(b),b=g.Kf(b))a.B=g.sq(b,c)},D0=function(a,b,c){c=void 0===c?!0:c;
a.player.Ff("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&bVa(a);c=[];d=new g.Dv(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.S().isMobile||(a.u=new g.V({F:"div",L:"ytp-ce-shadow"}),g.KI(a.player,a.u.element,4),a.C=new g.jH(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=cVa(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.KI(a.player,f.element,4);var k=new g.Dv(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);dVa(a,
f,e)}else g.Eu(new g.Dr("buildEndscreenElement null",e))}a.player.Wd(c);a.wb()}},bVa=function(a){var b=g.Nu(),c=g.Ou();
c&&b&&a.endscreen.visualElement&&g.Su(void 0,c,b,[a.endscreen.visualElement])},cVa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Ba:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.ix||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:E0(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:F0(a,b.targetUrl),tabindex:"-1"},R:[{F:"div",Ba:["ytp-ce-video-title","ytp-webkit-ellipsis"],T:{dir:g.wo(b.title||"")},Z:b.title},{F:"div",L:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Z:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={F:"div",Ba:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.ix||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:E0(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:F0(a,b.targetUrl),tabindex:"-1"},R:[{F:"div",Ba:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],T:{dir:g.wo(b.title||"")},Z:b.title},{F:"div",L:"ytp-ce-playlist-count",
R:[{F:"div",L:"ytp-ce-playlist-icon"},{F:"div",L:"ytp-ce-playlist-count-text",Z:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={F:"div",Ba:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.ix||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"a",Ba:["ytp-ce-channel-title","ytp-ce-link"],T:{href:F0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.wo(b.title||"")},Z:b.title},b.subscribeButton?{F:"div",L:"ytp-ce-subscribe-container",R:[{F:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",L:"ytp-ce-channel-subscribers-text",Z:b.subscribersText}:"",b.metadata?{F:"div",Ba:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Z:b.metadata}:""]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:E0(b)}]};c=new g.V(c);var d=g.zg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.ho(d,"ytp-ce-subscribe-button");if(a.player.S().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.dK(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Ba:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.ix||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"div",L:"ytp-ce-website-title",T:{dir:g.wo(b.title||"")},Z:b.title},{F:"div",L:"ytp-ce-website-metadata",Z:b.metadata},{F:"a",Ba:["ytp-ce-website-goto","ytp-ce-link"],T:{href:F0(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:E0(b)},{F:"div",L:"ytp-ce-expanding-icon",T:eVa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",L:"ytp-ce-merchandise-price-container",R:[{F:"div",L:"ytp-ce-merchandise-price",Z:b.productPrice}]},b.additionalFeesText&&c.R.push({F:"div",L:"ytp-ce-merchandise-additional-fees",Z:b.additionalFeesText})),a={F:"div",Ba:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":b.ix||"","aria-hidden":"true"},R:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",R:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},
{F:"div",L:"ytp-ce-expanding-overlay-content",R:[{F:"div",L:"ytp-ce-expanding-overlay-body",R:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{F:"div",L:"ytp-ce-merchandise-title",T:{dir:g.wo(b.title||"")},Z:b.title},c,{F:"div",L:"ytp-ce-merchandise-metadata",Z:b.metadata},{F:"a",Ba:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:F0(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:E0(b)},{F:"div",L:"ytp-ce-merchandise-invideo-cta-container",
R:[{F:"div",L:"ytp-ce-merchandise-invideo-cta",Z:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.ho(c.element,"ytp-ce-placeholder");return c},E0=function(a){if(a.nN)var b=a.nN.thumbnails;
return eVa(b?b[b.length-1].url:null)},eVa=function(a){return a?{style:"background-image: url("+a+")"}:{}},dVa=function(a,b,c){function d(m){m&&(b.La("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.P(m,"focus",f),b.P(m,"blur",k))}
function e(m){a.I+=m;0<a.I?(g.ho(b.element,"ytp-ce-force-expand"),G0(a,c.id,!0)):(g.jo(b.element,"ytp-ce-force-expand"),g.jo(b.element,"ytp-ce-element-hover"),G0(a,c.id,!1))}
function f(){e(1)}
function k(){e(-1)}
b.La("mouseenter",function(){H0(a,b,c)});
b.La("mouseleave",function(){I0(a,b,c)});
a.player.S().isMobile||b.La("click",function(){g.ho(b.element,"ytp-ce-element-hover")});
b.La("click",function(m){fVa(a,c,m)});
b.La("keypress",function(m){fVa(a,c,m)});
b.La("focus",function(){H0(a,b,c)});
b.La("blur",function(){I0(a,b,c)});
b.La("touchstart",function(){H0(a,b,c)});
var l=g.Bg("ytp-ce-expanding-overlay-hider",b.element);l&&b.P(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.jo(b.element,"ytp-ce-element-hover");g.jo(b.element,"ytp-ce-force-expand")});
b.La("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.Bg("ytp-sb-subscribe",b.element));d(g.Bg("ytp-sb-unsubscribe",b.element));b.La("focus",f);b.La("blur",k)},fVa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.go(d,"ytp-ce-element");){g.go(d,"subscribe-label")&&J0(a,b);
if(g.go(d,"ytp-ce-channel-subscribe"))return;d=g.Lg(d)}if(!d||g.go(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])I0(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.g1)J0(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Mf(F0(a,b.targetUrl)),g.JH(g.Kf(c),void 0,b.sessionData);else{var e=g.VB(a.player.S())||a.player.getVideoData().D,f=function(){var k=F0(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.eq(k);e&&n&&(n.v||n.list)?
a.player.wl(n.v,l,n.list,!1,void 0,m||void 0):g.IH(k,l)};
J0(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},F0=function(a,b){a=a.player.S();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.eC(a)+b}else return"";return b},H0=function(a,b,c){g.go(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.ho(b.element,"ytp-ce-element-hover"):a.player.S().isMobile?(new g.K(function(){g.ho(b.element,"ytp-ce-element-hover")},200)).start():g.ho(b.element,"ytp-ce-element-hover"),K0(a,c.kX),G0(a,c.id,!0))},I0=function(a,b,c){g.jo(b.element,"ytp-ce-element-hover");
g.jo(b.element,"ytp-ce-force-expand");G0(a,c.id,!1)},G0=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.j[e].element,"ytp-ce-element-shadow-show",c)},K0=function(a,b,c){function d(){f||(e++,e===b.length&&(k.stop(),c&&c()))}
if(!b||0===b.length||C0(a))c&&c();else{b=gVa(a,b);var e=0,f=!1,k=new g.K(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Js(b[a],d)}},J0=function(a,b,c){K0(a,b.clickUrls,c);
(a=g.Ou())&&b.vX&&g.Yu(a,b.visualElement)},gVa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(hVa(b[d],c));return a},hVa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},iVa=function(a){return"string"===typeof a?a:""},L0=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},jVa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},M0=function(a){return a.value?a.value:null},N0=function(a){if(!a)return null;
var b=g.Mf(iVa(a.value));b=g.Kf(b);if(!b)return null;var c=L0(a.target,kVa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new jVa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},lVa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},oVa=function(a){if(!a)return null;
var b=L0(a.type,mVa),c=L0(a.trigger,nVa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=N0(a?a:null);return b?new lVa(b,c,a):null},pVa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},rVa=function(a){return(a=qVa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},qVa=function(a,b){return g.Rb(a.action,b)},sVa=function(a,b){this.context=a;
this.j=b},P0=function(a){return a.customMessage?O0("div","iv-card-message",a.customMessage):""},Q0=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",L:"iv-card-image",T:{style:a},R:c}},R0=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(O0("li","",c.value));return{F:"ul",L:"iv-card-meta-info",R:b}},O0=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.wo(c);return{F:a,T:b,Z:c}},tVa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.tx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.tx+");");c.dir=g.wo(a.customMessage);var d=[{F:"span",Z:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",L:"iv-card-link-icon"}));return{F:"div",Ba:b,T:c,R:d}},S0=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},uVa=function(a,b){this.merchant=a;
this.price=b},vVa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},wVa=function(a,b){return b?b:vVa(a)?"current":"new"},T0=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.jb=!1;this.Ta=new Map;this.Ua=new Map;this.context.G.addEventListener(g.Fv("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.Gv("annotations_module"),function(d){(d=c.Ua.get(d))&&d.apply(c)})},U0=function(a,b,c,d,e,f,k){a.context.j.La(b,"click",function(l){a.OE(c,d,e,f||[],k||0,l)});
a.context.j.La(b,"touchstart",function(){a.jb=!1});
a.context.j.La(b,"touchmove",function(){a.jb=!0})},xVa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},V0=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
zR:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
BD:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Y0=function(a,b,c){T0.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ja=this.Lb=this.B=this.isInitialized=!1;this.oa=null;this.cards=[];this.qb=this.N=this.Fa=this.D=this.Oa=this.j=null;this.W=[];this.Y=this.J=this.kf=this.Da=null;this.I=0;this.va=new g.K(function(){},c.U.df?4E3:3E3);
g.I(this,this.va);this.fb=new g.K(function(){});
g.I(this,this.fb);this.ma=new sVa(c,function(e,f,k,l,m,n){U0(d,e,f,k,l,m,n)});
this.V=new g.V({F:"div",L:"iv-drawer",T:{id:"iv-drawer"},R:[{F:"div",L:"iv-drawer-header",T:{"aria-role":"heading"},R:[{F:"span",L:"iv-drawer-header-text"},{F:"button",Ba:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Ukryj karty",tabindex:"0"}}]},{F:"div",L:"iv-drawer-content"}]});g.I(this,this.V);this.C=this.V.element;this.eb=new g.jH(this.V,330);g.I(this,this.eb);this.Jb=g.Bg("iv-drawer-header-text",this.C);this.u=g.Bg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Lb&&W0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Lb=d.B)&&X0(d)});
this.G.addEventListener("videodatachange",this.Ep.bind(this))},yVa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){W0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){X0(a)});
var c=b.headerText;g.Ng(a.Jb,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.Hu(b.trackingParams);a.J=g.Hu(b.closeTrackingParams);a.kf=g.Hu(b.iconTrackingParams)},zVa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.S().experiments.gb("enable_error_corrections_infocard");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){d=b.teaser.simpleCardTeaserRenderer;var e=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Sv(d.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},Ul:null,hj:d.trackingParams?g.Hu(d.trackingParams):null,kf:e&&e.trackingParams?g.Hu(e.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,tx:null,title:"",customMessage:"",url:null,onClickCommand:d.onTapCommand||null};Z0(a,b)}else if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Sv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:$0(a,
c,b,d),sponsored:!1,tracking:V0(d,e,d.command),Ul:d.trackingParams?g.Hu(d.trackingParams):null,hj:e.trackingParams?g.Hu(e.trackingParams):null,kf:f&&f.trackingParams?g.Hu(f.trackingParams):null,imageUrl:a1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Sv(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,tx:null,title:d.title?g.Sv(d.title):"",customMessage:d.callToAction?g.Sv(d.callToAction):"",url:d.command.urlEndpoint.url?N0({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.command.urlEndpoint.url}):null,onClickCommand:null};Z0(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.Sv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:$0(a,
c,b,d),sponsored:!1,tracking:V0(d,e,d.endpoint),Ul:d.trackingParams?g.Hu(d.trackingParams):null,hj:e.trackingParams?g.Hu(e.trackingParams):null,kf:f&&f.trackingParams?g.Hu(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Sv(d.customText):null,profileImageUrl:a1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Sv(d.channelName):"",metaInfo:[d.subscriberCountText?g.Sv(d.subscriberCountText):""],url:N0({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId}),onClickCommand:null};Z0(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.Sv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:$0(a,c,b,d),sponsored:!1,tracking:V0(d,e,d.action),Ul:d.trackingParams?g.Hu(d.trackingParams):null,hj:e.trackingParams?g.Hu(e.trackingParams):null,kf:f&&f.trackingParams?g.Hu(f.trackingParams):null,Tz:a1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Sv(d.customMessage):null,playlistVideoCount:g.Sv(d.playlistVideoCount),title:d.playlistTitle?g.Sv(d.playlistTitle):"",metaInfo:[d.channelName?
g.Sv(d.channelName):"",d.videoCountText?g.Sv(d.videoCountText):""],url:N0({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:xVa(d.action)}),onClickCommand:null};Z0(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.Sv(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:$0(a,c,b,d),sponsored:!1,tracking:V0(d,e,d.action),Ul:d.trackingParams?g.Hu(d.trackingParams):null,hj:e.trackingParams?g.Hu(e.trackingParams):null,kf:f&&f.trackingParams?g.Hu(f.trackingParams):null,Tz:a1(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Sv(d.lengthString):null,customMessage:d.customMessage?g.Sv(d.customMessage):null,title:d.videoTitle?g.Sv(d.videoTitle):"",metaInfo:[d.channelName?
g.Sv(d.channelName):"",d.viewCountText?g.Sv(d.viewCountText):""],isLiveNow:!!d.badge,url:N0({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:xVa(d.action)}),onClickCommand:null};Z0(a,b)}a.I++},a1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},$0=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},BVa=function(a,b){if(b=AVa(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.Kg(b.FF),g.Zb(a.cards,b),a.QA(),b1(a)},W0=function(a,b,c){if(!a.B){a.eb.show();
a.Oa=new g.K(function(){g.ho(a.context.G.getRootNode(),g.DO.IV_DRAWER_OPEN)},0);
a.Oa.start();a.oa=g.lt(a.u,"mousewheel",function(k){a.va.start();k.preventDefault();k=k||window.event;var l=0;"MozMousePixelScroll"==k.type?l=0==(k.axis==k.HORIZONTAL_AXIS)?k.detail:0:window.opera?l=k.detail:l=0==k.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?k.wheelDeltaY/-30:k.wheelDeltaY/-1.2:k.wheelDelta/-1.6:k.wheelDeltaY/-3;if(k=l)a.u.scrollTop+=k});
a.B=!0;var d=g.Ou();d&&a.Da&&a.J&&g.Wu(d,[a.Da,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.YO||(f.YO=!0,CVa(a.context.logger,f.card.tracking.impression,b)),d&&g.Wu(d,[f.card.Ul]);p0(a.G);c&&(a.D=new g.K(function(){a.Fa=a.N;a.qb.focus()},330),a.D.start())}},X0=function(a){a.B&&(a.eb.hide(),g.mt(a.oa),a.oa=null,g.jo(a.context.G.getRootNode(),g.DO.IV_DRAWER_OPEN),a.B=!1,p0(a.G),a.D&&a.D.stop(),a.D=new g.K(function(){a.Fa&&(a.Fa.focus(),a.Fa=null)},330),a.D.start())},
EVa=function(a){g.io(a.element,[g.DO.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.KI(a.G,a.C,5);DVa(a);a.N=g.Bg("ytp-cards-button",a.G.getRootNode());a.qb=g.Bg("iv-drawer-close-button",a.C);a.isInitialized=!0},DVa=function(a){var b=g.Bg("iv-drawer-close-button",a.C);
a.context.j.La(b,"click",a.UV,a);a.context.j.La(a.u,"touchend",function(){a.va.start()});
a.context.j.La(a.u,"scroll",a.gW,a);a.context.u.subscribe("onHideControls",function(){a.Ja=!0});
a.context.u.subscribe("onShowControls",function(){a.Ja=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ja=g.go(a.G.getRootNode(),"ytp-autohide")});
a.W.push(g.Gt("iv-button-shown",a.EX,a));a.W.push(g.Gt("iv-button-hidden",a.DX,a));a.W.push(g.Gt("iv-teaser-shown",a.xU,a));a.W.push(g.Gt("iv-teaser-hidden",a.FX,a));a.W.push(g.Gt("iv-teaser-clicked",a.wU,a))},FVa=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,k=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===k.key&&(f=void 0,(k=null==(f=k.value)?void 0:f.markers)&&0<k.length))return d=void 0,b.startMs=(null==(d=k[0].markerRenderer)?void 0:d.timeRangeStartMillis)||0,a.Y=null,!0}}a.Y=b;return!1},Z0=function(a,b){if(b.onClickCommand&&b.onClickCommand.changeEngagementPanelVisibilityAction&&"engagement-panel-error-corrections"===b.onClickCommand.changeEngagementPanelVisibilityAction.targetId){a.Y=
b;
var c=!0}else c=!1;if(!c||FVa(a,b))if(c=GVa(a,b)){var d={card:b,FF:c.element,YO:!1};if(!b.onClickCommand){a.isInitialized||EVa(a);BVa(a,b.id);var e=HVa(a,d);g.ec(a.cards,e,0,d);c.xa(a.u,e);a.QA()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,b1(a),IVa(a,d),W0(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&JVa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){JVa(a,d)}),b1(a))}},GVa=function(a,b){switch(b.type){case "simple":a=
a.ma;
var c=b.displayDomain?{F:"div",L:"iv-card-image-text",Z:b.displayDomain}:void 0;var d=tVa(b);c={F:"div",Ba:["iv-card"],R:[{F:"a",L:"iv-click-target",T:{href:b.url?M0(b.url)||"":""},R:[Q0(b.imageUrl,c),{F:"div",L:"iv-card-content",R:[O0("h2",void 0,b.title),d]}]}]};c=new g.V(c);S0(a,g.Ag("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ma,c={F:"div",Ba:["iv-card","iv-card-channel"],R:[{F:"a",Ba:["iv-click-target"],T:{href:M0(b.url)||"","data-ytid":b.channelId},R:[Q0(b.profileImageUrl),
{F:"div",L:"iv-card-content",R:[P0(b),{F:"h2",L:"iv-card-primary-link",Z:b.title},R0(b)]}]}]},c=new g.V(c),S0(a,g.Ag("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ma,c={F:"div",Ba:["iv-card","iv-card-playlist"],R:[{F:"a",L:"iv-click-target",T:{href:M0(b.url)||""},R:[Q0(b.Tz,{F:"div",L:"iv-card-image-overlay",R:[{F:"span",L:"iv-card-playlist-video-count",Z:b.playlistVideoCount}]}),{F:"div",L:"iv-card-content",R:[P0(b),O0("h2","iv-card-primary-link",b.title),R0(b)]}]}]},c=new g.V(c),
S0(a,g.Ag("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ma;var e=!g.Vb(b.offers);c=["iv-card"];d="";var f=tVa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({F:"div",L:"iv-card-offer-price",Z:f.price}),f.merchant&&e.push({F:"div",L:"iv-card-offer-merchant",Z:f.merchant}),f={F:"div",R:e});e=b.url?M0(b.url)||"":"";c={F:"div",Ba:c,T:{tabindex:"0"},R:[{F:"a",Ba:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{F:"div",L:"iv-card-content",R:[b.sponsored?{F:"div",L:"iv-card-sponsored",R:["Sponsorowane",{F:"div",L:"iv-ad-info-container",R:[{F:"div",L:"iv-ad-info",Z:"{{adInfo}}"},{F:"div",L:"iv-ad-info-icon-container",R:[{F:"div",L:"iv-ad-info-icon"},{F:"div",L:"iv-ad-info-callout"}]}]}]}:"",{F:"a",L:"iv-click-target",T:{href:e},R:[O0("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.Gg("span");g.Ng(d,"Widzisz ten produkt, poniewa\u017c naszym zdaniem jest on zwi\u0105zany z\u00a0Twoim filmem. Google mo\u017ce otrzymywa\u0107 wynagrodzenie od sprzedawcy.");
c.Ld(d,"adInfo");S0(a,g.Ag("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ma,d=b.videoDuration?{F:"span",L:"iv-card-video-duration",Z:b.videoDuration}:void 0,f=b.isLiveNow?{F:"span",Ba:["yt-badge","yt-badge-live"],Z:"AKTUALNIE NA \u017bYWO"}:null,e={F:"div",Ba:["iv-card","iv-card-video"],R:[{F:"a",L:"iv-click-target",T:{href:(null==(c=b.url)?void 0:M0(c))||""},R:[Q0(b.Tz,d),{F:"div",L:"iv-card-content",R:[P0(b),O0("h2","iv-card-primary-link",b.title),R0(b),f]}]}]},c=new g.V(e),
S0(a,g.Ag("iv-click-target",c.element),b,b.url),c;default:return null}},HVa=function(a,b){if(0===a.cards.length)return 0;
a=g.Sb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},KVa=function(a){return a.j?"productListing"===a.j.card.type:g.lk(a.cards,function(b){return"productListing"===b.card.type})},b1=function(a){g.N(a.G.getRootNode(),"ytp-cards-shopping-active",KVa(a))},JVa=function(a,b){if(!g.go(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Ou(),d=a.j?a.j.card.kf:a.kf;
c&&d&&g.Xu(c,[d]);a.j=b;b1(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.Nv(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.fb.isActive()||((!a.B||!a.va.isActive()&&a.Ja)&&IVa(a,b),a.fb.start(910+b.card.teaserDurationMs))}},IVa=function(a,b){a.V.ob?(b=new u0([0,
a.u.scrollTop],[0,b.FF.offsetTop],600,TUa),a.context.B.La(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.La(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.yG(a.V,!0),a.u.scrollTop=b.FF.offsetTop,g.yG(a.V,!1))},c1=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},AVa=function(a,b){return g.Rb(a.cards,function(c){return c.card.id===b})},d1=function(a,b,c){T0.call(this,a,b);
this.annotation=c;this.isActive=!1},LVa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},e1=function(a,b,c){d1.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},MVa=function(a,b){var c=void 0===c?0:c;
var d=RUa(b).width;g.hl(b,d);c=new w0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,SUa);g.I(a,c);a.context.B.La(c,"begin",function(){g.nl(b,!0)});
c.play()},PVa=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Ba:["iv-branding-context-name"],Z:b.channel_name}),d=a.createElement({F:"div",Ba:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.dK(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.xa(d));var f=a.createElement({F:"div",Ba:["iv-branding-context-subscribe-caret"]}),k=a.createElement({F:"div",Ba:["branding-context-container-inner"]});
k.appendChild(f);k.appendChild(c);k.appendChild(d);g.nl(k,!1);var l=a.createElement({F:"div",Ba:["branding-context-container-outer"]});l.appendChild(k);g.bl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.K(function(){NVa(a,k,l)},500);
g.I(a,a.B);a.context.j.La(a.element,"mouseover",function(){OVa(a,k,l,f,b.image_height)});
a.context.j.La(a.element,"mouseout",function(){a.B.start()})}},OVa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.ml(b);a.j||(b.style.width=g.gl(f.width,!0),c.style.width=g.gl(f.width,!0));g.bl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.bl(d,"right","1px");a.C=!0;g.nl(b,!0);a.D=new g.K(function(){g.ho(this.element,"iv-branding-active")},0,a);
a.D.start()}},NVa=function(a,b,c){g.jo(a.element,"iv-branding-active");
a.I=new g.K(function(){g.nl(b,!1);a.j||(c.style.width=g.gl(0,!0))},250);
a.I.start();a.C=!1},QVa=function(a,b,c,d,e,f,k){this.j=a;
this.B=b;this.U=c;this.videoData=d;this.logger=e;this.G=f;this.u=k},f1=function(a,b,c){d1.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.V=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Ba:["iv-promo-contents"]});this.D=new g.K(function(){d.j.setAttribute("aria-hidden","true");g.nl(d.B,!1);g.nl(d.u,!0)},700,this);
g.I(this,this.D)},RVa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promocja");a.element.tabIndex=0;var e=rVa(a.annotation),f=b.image_url;if(f){var k=a.createElement({F:"div",Ba:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",T:{src:f,"aria-hidden":"true"}});k.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",L:"iv-promo-video-duration",Z:b.video_duration}),k.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",L:"iv-promo-playlist-length",Z:b.playlist_length.toString()}),k.appendChild(f));e&&U0(a,k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",L:"iv-promo-txt"}),g.$f(f,M0(e)),a.j=f):a.j=a.createElement({F:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",R:[{F:"strong",
Z:b.text_line_1}]});var m=a.createElement({F:"p",R:[{F:"span",L:"iv-promo-link",Z:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Ba:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Ba:["iv-button","iv-promo-button"],R:[{F:"span",L:"iv-button-content",Z:f}]});var p=a.createElement({F:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&U0(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.ho(a.j,
"iv-click-target");e&&U0(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",R:[{F:"span",Z:b.text_line_1}]}),m=a.createElement({F:"p",R:[{F:"strong",Z:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Ba:["yt-badge","iv-promo-badge-live"],Z:"AKTUALNIE NA \u017bYWO"})),g.ho(a.j,"iv-click-target"),e&&U0(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);
p&&a.J.appendChild(p);c=a.createElement({F:"div",L:"iv-promo-actions"});a.u=a.createElement({F:"button",Ba:["iv-promo-expand","ytp-button"]});a.u.title="Wi\u0119kszy ekran";a.context.j.La(a.u,"click",function(q){g1(a,5E3,q)});
c.appendChild(a.u);g.nl(a.u,!1);a.context.j.La(a.element,"mouseover",a.NW,a);a.context.j.La(a.element,"mouseout",a.MW,a);a.context.j.La(a.element,"touchend",function(q){g1(a,5E3,q)});
a.B=a.createElement({F:"button",Ba:["iv-promo-close","ytp-button"]});a.B.title="Zamknij";a.context.j.La(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.IW:a.HW,a);c.appendChild(a.B);g.io(a.element,d);k&&(a.element.appendChild(k),n&&k.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},g1=function(a,b,c){c.stopPropagation();
SVa(a);TVa(a,b);a.j.focus()},UVa=function(a){a.isCollapsed||a.N||a.C||(g.ho(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},SVa=function(a){a.D.stop();
a.isCollapsed&&(g.ko(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.nl(a.u,!1),g.nl(a.B,!0))},TVa=function(a,b){a.C||(a.C=g.gh(function(){h1(this);
UVa(this)},b,a))},h1=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},VVa=function(a){this.G=a},CVa=function(a,b,c){b&&(c?i1(a,b.map(function(d){return g.Bn(d,c)})):i1(a,b))},i1=function(a,b,c,d){var e=1,f=void 0,k=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(k),l=!0,c())};
k=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Js(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},j1=function(a){g.YI.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new VVa(this.player);this.D=new g.mz(this);this.C=this.Pm=null;this.events=new g.mz(this);this.J=this.j=null;this.N=[];g.I(this,this.D);this.D.P(this.player,"onVideoAreaChange",function(){b.X("onVideoAreaChange")});
this.D.P(this.player,"onHideControls",function(){b.X("onHideControls")});
this.D.P(this.player,"onShowControls",function(){b.X("onShowControls")});
this.D.P(this.player,"resize",function(d){b.X("resize",d)});
this.D.P(this.player,"presentingplayerstatechange",function(d){b.X("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.yU,this);this.subscribe("resize",this.HC,this);this.player.S().W.subscribe("vast_info_card_add",this.kQ,this);g.I(this,this.events);this.V=this.createElement({F:"div",L:"video-custom-annotations"});this.u=new g.V({F:"div",Ba:["ytp-player-content","ytp-iv-player-content"]});g.I(this,this.u);g.KI(this.player,this.u.element,4);this.u.hide();this.B=new g.V({F:"div",Ba:["ytp-iv-video-content"]});g.I(this,this.B);a=this.createElement({F:"div",L:"video-annotations"});
a.appendChild(this.V);this.B.element.appendChild(a);this.Qs()&&this.load();var c=this.createElement({F:"style"});(g.yg("HEAD")[0]||document.body).appendChild(c);g.Fe(this,function(){g.Kg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},WVa=function(a){a=a.createElement({F:"div",
Ba:["annotation","annotation-type-custom"]});g.nl(a,!1);return a},XVa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.yG(a.u,b);g.yG(a.B,b)},YVa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(YVa(a,e))}return c},aWa=function(a){var b=a.player.getVideoData();
if(b.Ua){var c=a.player.S().W.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,k){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(k=g.mq(k)&&k.responseXML?k.responseXML:null)&&k1(a,k)}};
g.rr()&&(d.onFinish=ZVa(a,d.onFinish));d.postParams={ic_only:"1"};$Va(d,c);g.sq(b.Ua,d)}}},$Va=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.vx&&(a.postParams.ic_coll=b.vx);b.VA&&(a.postParams.ic_xml=b.VA);b.Xz&&(a.postParams.ic_track=b.Xz)},bWa=function(a){var b=new g.V({F:"div"});
g.nl(b.element,!1);var c=new Y0(a.player,b.element,l1(a));g.I(c,b);b.xa(a.u.element);c.Gz();return c},l1=function(a){if(!a.J){var b=new x0(a);
g.I(a,b);var c=new g.fj(a);g.I(a,c);a.J=new QVa(b,c,a.player.S(),a.player.getVideoData(),a.logger,a.player,a.Oe)}return a.J},k1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Ou();if(e){var f=g.Nu();f&&g.Su(void 0,e,f,[g.Hu(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=YVa(a,b[d]);e=null;try{if(f){var k=f.id,l=/.+/;var m="string"===typeof k&&null!=l&&null!=k&&k.match(l)?k:"";var n=L0(f.type,cWa),p=L0(f.style,dWa),q=iVa(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=oVa;if(null==u)var x=null;else if(g.Na(u)){l=[];for(var y=g.r(u),z=y.next();!z.done;z=y.next()){var D=f(z.value);
D&&l.push(D)}x=l}else{var H=f(u);x=H?[H]:[]}e=m&&n?new pVa(m,n,p,x,t):null}else e=null}catch(Y){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var J=WVa(f),L=null;switch(l.type){case "branding":if(f.player.S().Nc)break;f.u.element.appendChild(J);L=new e1(J,l1(f),l);break;case "promotion":g.KI(f.player,J,4),L=new f1(J,l1(f),l)}L&&L.Gz();if(f=L)g.I(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=bWa(a),g.I(a,a.j));if("card"===e.type){c=a.j;var ba=e&&e.data&&e.data.card_type;
f=e.data;if(ba)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,zR:l.teaser_impression,BD:l.teaser_click},J=f.tracking_params||{},L=null,ba){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ul:J.card?g.Hu(J.card):null,hj:J.teaser?g.Hu(J.teaser):null,kf:J.icon?g.Hu(J.icon):
null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:N0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};Z0(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
Ul:J.card?g.Hu(J.card):null,hj:J.teaser?g.Hu(J.teaser):null,kf:J.icon?g.Hu(J.icon):null,Tz:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:N0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};Z0(c,e);break;case "productListing":f.signin_url&&(L=N0({target:"current",value:f.signin_url}));ba=[];for(var M=f.offers||[],ta=0;ta<M.length;ta++)ba.push(new uVa(g.og(M[ta].merchant),
g.og(M[ta].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ul:J.card?g.Hu(J.card):null,hj:J.teaser?g.Hu(J.teaser):null,kf:J.icon?g.Hu(J.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,tx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:N0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Hka:L,Gka:f.signin_title?f.signin_title:void 0,Fka:f.signin_message?f.signin_message:void 0,offers:ba,onClickCommand:null};Z0(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ul:J.card?g.Hu(J.card):
null,hj:J.teaser?g.Hu(J.teaser):null,kf:J.icon?g.Hu(J.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,tx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:N0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};Z0(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ul:J.card?g.Hu(J.card):null,hj:J.teaser?g.Hu(J.teaser):null,kf:J.icon?g.Hu(J.icon):null,Tz:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:N0({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},Z0(c,e)}}else yVa(a.j,e);c=
!0}}c&&(p0(a.player),a.HC())},eWa=function(a,b){var c=!1;
a.j||(a.j=bWa(a),g.I(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(zVa(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.Sv(b.headerText):"",g.Ng(c.Jb,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.Hu(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.Hu(b.closeButton.infoCardIconRenderer.trackingParams):null,c.kf=b.icon.infoCardIconRenderer.trackingParams?
g.Hu(b.icon.infoCardIconRenderer.trackingParams):null,p0(a.player),a.HC())},fWa=function(a,b,c,d,e){if(!a.player.S().Nc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new lVa("openUrl","click",new jVa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Sv(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.Sv(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Sv(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.Sv(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.Sv(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Sv(b.subscribedButtonText),unsubscribeCount:k||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new pVa(c,"branding","branding",f,d);l=WVa(a);a.u.element.appendChild(l);f=new e1(l,l1(a),f);f.Gz();g.I(f,f);a.I[c]=f}},ZVa=function(a,b){return function(){var c=
g.Ca.apply(0,arguments);
a.isDisposed()||a.N.push(g.En.Vg(function(){b.apply(null,g.v(c))}))}},gWa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.DI.prototype.Nv=g.da(17,function(a,b){var c=g.pJ(this.ib());c&&c.Nv(a,b)});
var r0={},s0=null;g.Ua(u0,g.so);g.h=u0.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Lc())return!1;t0(this);this.startTime=a=g.Ta();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.DC();this.zj("play");-1==this.j&&this.zj("resume");this.j=1;var b=g.Qa(this);b in r0||(r0[b]=this);VUa();WUa(this,a);return!0};
g.h.stop=function(a){t0(this);this.j=0;a&&(this.progress=1);XUa(this,this.progress);this.zj("stop");this.Yy()};
g.h.pause=function(){this.Lc()&&(t0(this),this.j=-1,this.zj("pause"))};
g.h.ea=function(){0==this.j||this.stop(!1);this.zj("destroy");u0.Ke.ea.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.NE=function(){this.zj("animate")};
g.h.zj=function(a){this.dispatchEvent(new YUa(a,this))};
g.Ua(YUa,g.Ge);g.Ua(v0,u0);v0.prototype.C=function(){};
v0.prototype.NE=function(){this.C();v0.Ke.NE.call(this)};
v0.prototype.Yy=function(){this.C();v0.Ke.Yy.call(this)};
v0.prototype.DC=function(){this.C();v0.Ke.DC.call(this)};
g.Ua(w0,v0);w0.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(x0,g.G);x0.prototype.La=function(a,b,c,d){c=(0,g.Ra)(c,d||this.u);a=g.lt(a,b,c);this.j.push(a);return a};
x0.prototype.nC=function(a,b,c,d){c=(0,g.Ra)(c,d||this.u);a=g.Bpa(a,b,c);this.j.push(a);return a};
x0.prototype.xc=function(a){g.mt(a);g.Zb(this.j,a)};
x0.prototype.ea=function(){g.mt(this.j);this.j.length=0;g.G.prototype.ea.call(this)};g.w(B0,g.YI);g.h=B0.prototype;g.h.load=function(){g.YI.prototype.load.call(this);if(!C0(this)){var a=g.Ixa(this.player.getVideoData());a?(a=A0(a,$Ua(this)),D0(this,a,!1)):aVa(this)}};
g.h.unload=function(){D0(this,null);this.B&&(this.B.abort(),this.B=null);g.YI.prototype.unload.call(this)};
g.h.cg=function(a,b){return C0(this)?"loadCustomEndscreenRenderer"===a?(a=A0(b,"new"),D0(this,a),!0):null:null};
g.h.getOptions=function(){return C0(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.wb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<hWa.length;f++){var k=Math.abs(b.width-hWa[f]);if(-1===e||d>=k)e=f,d=k}d=iWa[e];this.u&&g.bl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
k=this.D[f],e&&k){var l=k.width*c/k.aspectRatio,m=Math.round(k.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(k.left*a.width),p=a.top+Math.round(k.top*a.height);g.ll(e.element,m,f);g.hl(e.element,n,p);this.W&&(g.ko(e.element,jWa),256<m||256<f?g.ho(e.element,"ytp-ce-large-round"):96<m||96<f?g.ho(e.element,"ytp-ce-medium-round"):g.ho(e.element,"ytp-ce-small-round"));g.ko(e.element,kWa);m=k.left+k.width/2;k=k.top+l/2;g.ho(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":
.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ko(e.element,iWa);g.ho(e.element,d);(e=g.zg(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.bl(e,"height",f+"px")}}}}};
g.h.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())K0(this,this.endscreen.impressionUrls),(a=g.Ou())&&this.endscreen.visualElement&&g.Tu(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.ho(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.ho(b,"ytp-ce-shown");K0(this,c.impressionUrls);(b=g.Ou())&&g.Tu(b,c.visualElement);this.player.S().B&&this.player.Ma("endscreenelementshown",
a)}};
g.h.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.jo(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.jo(b,"ytp-ce-shown");this.player.S().B&&this.player.Ma("endscreenelementhidden",a)}};
g.h.d0=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.ko(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var hWa=[346,426,470,506,570,640,853,1280,1920],iWa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),kWa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],jWa=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var kVa={m7:"current",oda:"new"};var mVa={CLOSE:"close",Ida:"openUrl",SUBSCRIBE:"subscribe"},nVa={V3:"click",CLOSE:"close",O8:"hidden",rfa:"rollOut",sfa:"rollOver",pga:"shown"};var dWa={Q2:"anchored",tS:"branding",CHANNEL:"channel",l7:"cta",S8:"highlightText",y$:"label",PLAYLIST:"playlist",Dea:"popup",Gga:"speech",SUBSCRIBE:"subscribe",bha:"title",VIDEO:"video",Hia:"website"},cWa={tS:"branding",I3:"card",E7:"drawer",Q8:"highlight",lba:"marker",Nea:"promotion",TEXT:"text",kja:"widget"};g.w(T0,g.G);g.h=T0.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.Dv(a,b,{id:c,namespace:"annotations_module"});d&&this.Ta.set(a,d);e&&this.Ua.set(a,e);this.context.G.Wd([a])};
g.h.Gz=function(){this.context.u.subscribe("resize",this.QA,this)};
g.h.OE=function(a,b,c,d,e,f){if(this.jb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Kg(this.element)};
g.h.QA=function(){};
g.h.navigate=function(a,b,c,d){var e=this,f=M0(a);if(f){var k=wVa(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.D||!1,n=g.eq(f||"");m&&n&&(n.v||n.list)?e.context.G.wl(n.v,b,n.list,!1):g.JH(f||"","current"===k?"_top":void 0,b)};
"new"===k&&(l(),l=null);i1(this.context.logger,c,l,d);vVa(f)||(c=g.Ou(),d=b.itct,c&&d&&g.Yu(c,g.Hu(d)))}};
g.h.ea=function(){this.Ta.clear();this.Ua.clear();g.G.prototype.ea.call(this)};
g.h.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.w(Y0,T0);g.h=Y0.prototype;g.h.Ep=function(){this.Y&&Z0(this,this.Y)};
g.h.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.ml(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.QA=function(){var a=this.isAvailable();g.nl(this.element,a);g.N(this.context.G.getRootNode(),g.DO.IV_DRAWER_ENABLED,a);p0(this.G)};
g.h.destroy=function(){this.G.Nv(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.Ht(this.W);g.mt(this.oa);this.Oa&&this.Oa.dispose();this.D&&this.D.dispose();T0.prototype.destroy.call(this)};
g.h.UV=function(){if(this.B){i1(this.context.logger,c1(this).tracking.close);var a=g.Ou();a&&this.J&&g.Yu(a,this.J);X0(this)}};
g.h.gW=function(){g.N(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.h.EX=function(){var a=g.Ou(),b=c1(this);b=b?b.kf:this.kf;a&&b&&g.Wu(a,[b])};
g.h.DX=function(){var a=g.Ou(),b=c1(this);b=b?b.kf:this.kf;a&&b&&g.Xu(a,[b])};
g.h.xU=function(){var a=c1(this);i1(this.context.logger,a.tracking.zR);var b=g.Ou();b&&a&&g.Wu(b,[a.hj,a.kf])};
g.h.FX=function(){var a=g.Ou(),b=c1(this);a&&b&&g.Xu(a,[b.hj])};
g.h.wU=function(a){var b=c1(this),c=g.Ou();this.j?a?(a=this.context.logger,i1(a,b.tracking.BD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.hj&&g.Yu(c,b.hj)):(a=this.context.logger,i1(a,b.tracking.BD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.kf&&g.Yu(c,b.kf)):(a=this.context.logger,i1(a,b.tracking.BD),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.kf&&g.Yu(c,this.kf))};g.w(d1,T0);d1.prototype.Gz=function(){T0.prototype.Gz.call(this);LVa(this)};
d1.prototype.show=function(){T0.prototype.show.call(this);var a=g.Ou(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Wu(a,[g.Hu(b.itct)])};
d1.prototype.hide=function(){T0.prototype.hide.call(this);var a=g.Ou(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Xu(a,[g.Hu(b.itct)])};g.w(e1,d1);
e1.prototype.show=function(){if(!this.isActive){d1.prototype.show.call(this);if(!this.J){g.ho(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Ba:["branding-img","iv-click-target"],T:{"aria-label":"Znak wodny kana\u0142u",src:a.image_url,width:a.image_width,height:a.image_height}});g.nl(this.u,!1);var b=this.context.U.K("html5_player_branding_button_killswitch")?this.createElement({F:"div",Ba:["branding-img-container"]}):this.createElement({F:"button",Ba:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=rVa(this.annotation);c&&(b=this.context.U.K("html5_player_branding_button_killswitch")?this.u:b,U0(this,b,c,this.annotation.id,a.session_data));PVa(this,a);this.J=!0}g.nl(this.element,!0);this.isActive=!0;this.u&&MVa(this,this.u)}};
e1.prototype.hide=function(){this.isActive&&(d1.prototype.hide.call(this),g.nl(this.element,!1),this.isActive=!1)};
e1.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);d1.prototype.destroy.call(this)};g.w(f1,d1);g.h=f1.prototype;g.h.show=function(){this.isActive||(d1.prototype.show.call(this),this.V||(RVa(this),this.V=!0),g.nl(this.element,!0),g.gh(function(){g.jo(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,h1(this),SVa(this),TVa(this,this.I))};
g.h.hide=function(){this.isActive&&(g.ho(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.h.OE=function(a,b,c,d,e,f){return this.isCollapsed?!1:d1.prototype.OE.call(this,a,b,c,d,e,f)};
g.h.NW=function(a){this.N=!0;g1(this,500,a)};
g.h.MW=function(){this.N=!1;UVa(this)};
g.h.HW=function(a){a.stopPropagation();this.hide()};
g.h.IW=function(a){a.stopPropagation();h1(this);this.isCollapsed=!0;g.ho(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();d1.prototype.destroy.call(this)};g.w(j1,g.YI);g.h=j1.prototype;g.h.cg=function(a,b){if(!gWa(this.player.S().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.HZ(b))&&k1(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(BVa(this.j,b),p0(this.player)),!0}return null};
g.h.getOptions=function(){return gWa(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Qs=function(){var a=this.player.S(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.aR||a.W.get(b.videoId)||g.TD(b)||g.UD(b)?!0:!1};
g.h.HC=function(){if(this.B){var a=this.player.Ya().getVideoContentRect(!0);g.ll(this.B.element,a.width,a.height);g.hl(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Ej();a=this.j;b=b.width;g.N(a.C,"iv-drawer-small",426>=b);g.N(a.C,"iv-drawer-big",1280<=b)}};
g.h.yU=function(a){XVa(this,a.state);g.U(a.state,2)&&(this.Rh()&&this.Tl()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Nv(!1))};
g.h.load=function(){function a(k){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(k=g.mq(k)&&k.responseXML?k.responseXML:null)&&(k1(b,k),g.ho(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.YI.prototype.load.call(this);XVa(this,this.player.xb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.rr()&&(a=ZVa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.S().W.get(d);f&&$Va(e,f);f=f&&(f.VA||f.vx);if(!c.hn||f)c.Ua?this.C=g.sq(c.Ua,e):(this.Pm=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Pm));
g.KI(this.player,this.B.element,4);this.HC();(f=g.TD(c))&&eWa(this,f);(f=g.UD(c))&&f.featuredChannel&&fWa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.h.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ua&&(this.Pm&&(this.player.removeEventListener("videodatachange",this.Pm),this.Pm=null),this.C=g.sq(b.Ua,a))};
g.h.unload=function(){this.player.Ff("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,p0(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.YI.prototype.unload.call(this);this.B.detach();this.Pm&&(this.player.removeEventListener("videodatachange",this.Pm),this.Pm=null)};
g.h.kQ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?aWa(this):this.load())};
g.h.Rh=function(){return!!this.j&&this.j.isAvailable()};
g.h.Tl=function(){return!!this.j&&this.j.B};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Rh();this.j&&(a?c?W0(this.j,c,b):W0(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):X0(this.j))};
g.h.Nv=function(a,b){this.player.X(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.ea=function(){this.player.S().W.unsubscribe("vast_info_card_add",this.kQ,this);g.jo(this.player.getRootNode(),g.DO.IV_DRAWER_OPEN);for(var a=this.N,b=g.En,c=0,d=a.length;c<d;c++)b.xj(a[c]);this.N.length=0;g.YI.prototype.ea.call(this)};
g.h.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.XI("annotations_module",j1);g.XI("creatorendscreen",B0);})(_yt_player);
