(function(g){var window=this;'use strict';var JXa=function(a,b){a.Ma("onAutonavCoundownStarted",b)},H2=function(a,b,c){g.N(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Bf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.QC&&(b.lengthText?(e=b.lengthText||null,f=b.Zr||null):b.lengthSeconds&&(e=g.xH(b.lengthSeconds),f=g.xH(b.lengthSeconds,!0)));var k=!!d;d=k&&"RD"===g.MC(d).type;var l=b instanceof g.QC?b.isLivePlayback:null,m=b instanceof g.QC?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.ariaLabel||g.iF("Obejrzyj $TITLE",{TITLE:b.title}),
duration:e,timestamp:f,url:b.mm(),is_live:l,is_upcoming:m,is_list:k,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.So};b instanceof g.PC&&(c.playlist_length=b.playlistLength);a.update(c)},I2=function(a){var b=a.S(),c=b.j;
g.V.call(this,{F:"a",L:"ytp-autonav-suggestion-card",T:{href:"{{url}}",target:c?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},R:[{F:"div",Ba:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],T:{style:"{{background}}"},R:[{F:"div",T:{"aria-label":"{{timestamp}}"},Ba:["ytp-autonav-timestamp"],Z:"{{duration}}"},{F:"div",Ba:["ytp-autonav-live-stamp"],Z:"Na \u017cywo"},
{F:"div",Ba:["ytp-autonav-upcoming-stamp"],Z:"Wkr\u00f3tce"},{F:"div",L:"ytp-autonav-list-overlay",R:[{F:"div",L:"ytp-autonav-mix-text",Z:"Sk\u0142adanka"},{F:"div",L:"ytp-autonav-mix-icon"}]}]},{F:"div",Ba:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Z:"{{title}}"},{F:"div",Ba:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Z:"{{author}}"},{F:"div",Ba:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Z:"{{views_and_publish_time}}"}]});this.G=
a;this.suggestion=null;this.j=c;this.La("click",this.onClick);this.La("keypress",this.onKeyPress)},K2=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{F:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.I=b;this.D=void 0;this.u=0;b=a.S();var d=b.j;this.G=a;this.suggestion=null;this.onVideoDataChange("newdata",this.G.getVideoData());this.P(a,"videodatachange",this.onVideoDataChange);this.j=new g.V({F:"div",L:"ytp-autonav-endscreen-upnext-container",T:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},R:[{F:"div",
L:"ytp-autonav-endscreen-upnext-header"},{F:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",Z:"{{autoplayAlternativeHeader}}"},{F:"a",L:"ytp-autonav-endscreen-link-container",T:{href:"{{url}}",target:d?b.J:""},R:[{F:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",T:{style:"{{background}}"},R:[{F:"div",T:{"aria-label":"{{timestamp}}"},Ba:["ytp-autonav-timestamp"],Z:"{{duration}}"},{F:"div",Ba:["ytp-autonav-live-stamp"],Z:"Na \u017cywo"},{F:"div",Ba:["ytp-autonav-upcoming-stamp"],Z:"Wkr\u00f3tce"}]},
{F:"div",L:"ytp-autonav-endscreen-video-info",R:[{F:"div",L:"ytp-autonav-endscreen-premium-badge"},{F:"div",L:"ytp-autonav-endscreen-upnext-title",Z:"{{title}}"},{F:"div",L:"ytp-autonav-endscreen-upnext-author",Z:"{{author}}"},{F:"div",L:"ytp-autonav-view-and-date",Z:"{{views_and_publish_time}}"},{F:"div",L:"ytp-autonav-author-and-view",Z:"{{author_and_views}}"}]}]}]});g.I(this,this.j);this.j.xa(this.element);d||this.P(this.j.ya("ytp-autonav-endscreen-link-container"),"click",this.EL);this.G.Ab(this.element,
this,115127);this.G.Ab(this.j.ya("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({F:"div",L:"ytp-autonav-overlay"});g.I(this,this.overlay);this.overlay.xa(this.element);this.B=new g.V({F:"div",L:"ytp-autonav-endscreen-button-container"});g.I(this,this.B);this.B.xa(this.element);this.cancelButton=new g.V({F:"button",Ba:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],T:{"aria-label":"Anuluj autoodtwarzanie"},Z:"Anuluj"});g.I(this,this.cancelButton);
this.cancelButton.xa(this.B.element);this.cancelButton.La("click",this.GU,this);this.G.Ab(this.cancelButton.element,this,115129);this.playButton=new g.V({F:"a",Ba:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],T:{href:"{{url}}",role:"button","aria-label":"Odtw\u00f3rz nast\u0119pny film"},Z:"Odtw\u00f3rz teraz"});g.I(this,this.playButton);this.playButton.xa(this.B.element);this.playButton.La("click",this.EL,this);this.G.Ab(this.playButton.element,this,115130);this.C=
new g.K(function(){J2(c)},500);
g.I(this,this.C);this.DL();this.P(a,"autonavvisibility",this.DL)},N2=function(a){var b=a.G.Ej(!0,a.G.isFullscreen());
g.N(a.element,"ytp-autonav-endscreen-small-mode",a.jg(b));g.N(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.xD);g.N(a.G.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.G.We());g.N(a.G.getRootNode(),"countdown-running",a.Xi());g.N(a.element,"ytp-player-content",a.G.We());g.bl(a.overlay.element,{width:b.width+"px"});if(!a.Xi()){a.G.We()?L2(a,Math.round(M2(a)/1E3)):L2(a);b=!!a.suggestion&&!!a.suggestion.So;var c=a.G.We()||!b;g.N(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.N(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.yG(a.B,a.G.We())}},J2=function(a){var b=M2(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);L2(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Xi()?a.select(!0):a.Xi()&&a.C.start()},M2=function(a){if(a.G.isFullscreen()){var b;
a=null==(b=a.G.getVideoData())?void 0:b.hx;return-1===a||void 0===a?8E3:a}return 0<=a.G.mp()?a.G.mp():g.hA(a.G.S().experiments,"autoplay_time")||1E4},L2=function(a,b){b=void 0===b?-1:b;
a=a.j.ya("ytp-autonav-endscreen-upnext-header");g.Ig(a);if(0<=b){b=String(b);var c="Nast\u0119pny za $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Nast\u0119pny za $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Hg("Nast\u0119pny za $SECONDS".slice(0,d)));var e=g.Gg("span");g.fo(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ng(e,b);a.appendChild(e);a.appendChild(g.Hg("Nast\u0119pny za $SECONDS".slice(d+c.length)));return}}g.Ng(a,"Nast\u0119pny")},O2=function(a,b){g.V.call(this,{F:"div",
Ba:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},P2=function(a){g.V.call(this,{F:"div",
Ba:["ytp-upnext","ytp-player-content"],T:{"aria-label":"{{aria_label}}"},R:[{F:"div",L:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{F:"span",L:"ytp-upnext-top",R:[{F:"span",L:"ytp-upnext-header",Z:"Nast\u0119pny"},{F:"span",L:"ytp-upnext-title",Z:"{{title}}"},{F:"span",L:"ytp-upnext-author",Z:"{{author}}"}]},{F:"a",L:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"Odtw\u00f3rz nast\u0119pny film"},R:[{F:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},R:[{F:"circle",L:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",L:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",L:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",L:"ytp-upnext-bottom",R:[{F:"span",L:"ytp-upnext-cancel"},{F:"span",L:"ytp-upnext-paused",
Z:"Autoodtwarzanie jest wstrzymane"}]}]});this.api=a;this.cancelButton=null;this.D=this.ya("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.K(this.aB,5E3,this);this.u=0;var b=this.ya("ytp-upnext-cancel");this.cancelButton=new g.V({F:"button",Ba:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"Anuluj autoodtwarzanie"},Z:"Anuluj"});g.I(this,this.cancelButton);this.cancelButton.La("click",this.HU,this);this.cancelButton.xa(b);this.cancelButton&&
this.api.Ab(this.cancelButton.element,this,115129);g.I(this,this.C);this.api.Ab(this.element,this,18788);b=this.ya("ytp-upnext-autoplay-icon");this.P(b,"click",this.IU);this.api.Ab(b,this,115130);this.FL();this.P(a,"autonavvisibility",this.FL);this.P(a,"mdxnowautoplaying",this.tZ);this.P(a,"mdxautoplaycanceled",this.uZ);g.N(this.element,"ytp-upnext-mobile",this.api.S().isMobile)},KXa=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.hx;return-1===a||void 0===a?8E3:a}return 0<=a.api.mp()?a.api.mp():g.hA(a.api.S().experiments,"autoplay_time")||1E4},Q2=function(a,b){b=KXa(a,b);
var c=Math,d=c.min;var e=(0,g.Q)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Xi()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Xi()&&a.j.start()},R2=function(a){O2.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({F:"div",L:"ytp-suggestion-panel",R:[{F:"div",Ba:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Z:"Wi\u0119cej film\u00f3w"}]});this.J=new g.V({F:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new K2(this.player);g.I(this,this.u);this.u.xa(this.element);a.getVideoData().rd?this.j=this.u:(this.j=new P2(a),g.KI(this.player,this.j.element,4),g.I(this,this.j));this.overlay=new g.V({F:"div",
L:"ytp-autonav-overlay-cancelled-state"});g.I(this,this.overlay);this.overlay.xa(this.element);this.C=new g.mz(this);g.I(this,this.C);g.I(this,this.table);this.table.xa(this.element);this.table.show();g.I(this,this.J);this.J.xa(this.table.element);this.hide()},S2=function(a){var b=a.We();
b!==a.D&&(a.D=b,a.player.X("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},T2=function(a){O2.call(this,a,"subscribecard-endscreen");
this.j=new g.V({F:"div",L:"ytp-subscribe-card",R:[{F:"img",L:"ytp-author-image",T:{src:"{{profilePicture}}"}},{F:"div",L:"ytp-subscribe-card-right",R:[{F:"div",L:"ytp-author-name",Z:"{{author}}"},{F:"div",L:"html5-subscribe-button-container"}]}]});g.I(this,this.j);this.j.xa(this.element);var b=a.getVideoData();this.subscribeButton=new g.dK("Subskrybuj",null,"Rezygnuj\u0119 z subskrypcji",null,!0,!1,b.pk,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.subscribeButton);this.subscribeButton.xa(this.j.ya("html5-subscribe-button-container"));
this.P(a,"videodatachange",this.Ea);this.Ea();this.hide()},U2=function(a){var b=a.S(),c=g.qz||g.ZA?{style:"will-change: opacity"}:void 0,d=b.j,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.V.call(this,{F:"a",Ba:e,T:{href:"{{url}}",target:d?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},R:[{F:"div",L:"ytp-videowall-still-image",T:{style:"{{background}}"}},{F:"span",L:"ytp-videowall-still-info",R:[{F:"span",L:"ytp-videowall-still-info-bg",R:[{F:"span",L:"ytp-videowall-still-info-content",T:c,R:[{F:"span",L:"ytp-videowall-still-info-title",Z:"{{title}}"},{F:"span",
L:"ytp-videowall-still-info-author",Z:"{{author_and_views}}"},{F:"span",L:"ytp-videowall-still-info-live",Z:"Na \u017cywo"},{F:"span",L:"ytp-videowall-still-info-duration",Z:"{{duration}}"}]}]}]},{F:"span",Ba:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],R:[{F:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlista",{F:"span",L:"ytp-videowall-still-listlabel-length",R:[" (",{F:"span",Z:"{{playlist_length}}"},")"]}]},{F:"span",Ba:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
R:[{F:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Sk\u0142adanka",{F:"span",L:"ytp-videowall-still-listlabel-length",Z:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.mz(this);g.I(this,this.j);this.La("click",this.onClick);this.La("keypress",this.onKeyPress);this.j.P(a,"videodatachange",this.onVideoDataChange);a.Uh(this.element,this);this.onVideoDataChange()},V2=function(a){O2.call(this,a,"videowall-endscreen");
var b=this;this.G=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.N=null;this.u=new g.mz(this);g.I(this,this.u);this.I=new g.K(function(){g.ho(b.element,"ytp-show-tiles")},0);
g.I(this,this.I);var c=new g.V({F:"button",Ba:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"Poprzedni"},R:[g.DG()]});g.I(this,c);c.xa(this.element);c.La("click",this.MU,this);this.table=new g.vG({F:"div",L:"ytp-endscreen-content"});g.I(this,this.table);this.table.xa(this.element);c=new g.V({F:"button",Ba:["ytp-button","ytp-endscreen-next"],T:{"aria-label":"Dalej"},R:[g.EG()]});g.I(this,c);c.xa(this.element);c.La("click",this.LU,this);a.getVideoData().rd?this.j=new K2(a,!0):this.j=new P2(a);
g.I(this,this.j);g.KI(this.player,this.j.element,4);this.hide()},W2=function(a){return g.LI(a.player)&&a.nx()&&!a.C},X2=function(a){var b=a.We();
b!==a.J&&(a.J=b,a.player.X("autonavvisibility"))},Y2=function(a){g.YI.call(this,a);
var b=this;this.endScreen=null;this.j=this.u=this.B=!1;this.listeners=new g.mz(this);g.I(this,this.listeners);this.env=a.S();LXa(a)?(this.B=!0,MXa(this),this.j?this.endScreen=new R2(a):this.endScreen=new V2(this.player)):this.env.Pe?this.endScreen=new T2(this.player):this.endScreen=new O2(this.player);g.I(this,this.endScreen);g.KI(this.player,this.endScreen.element,4);NXa(this);this.listeners.P(a,"videodatachange",this.onVideoDataChange,this);this.listeners.P(a,g.Fv("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.P(a,g.Gv("endscreen"),function(c){b.onCueRangeExit(c)})},MXa=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.wi&&a.u===b.rd)return!1;a.j=b.wi;a.u=b.rd;return!0},LXa=function(a){a=a.S();
return!a.C&&a.Kc&&!a.Pe},NXa=function(a){a.player.Ff("endscreen");
var b=a.player.getVideoData();b=new g.Dv(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.Dv(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Wd([b,c])};
g.DI.prototype.mp=g.da(4,function(){return this.app.mp()});
g.TS.prototype.mp=g.da(3,function(){return this.getVideoData().oQ});g.w(I2,g.V);I2.prototype.select=function(){(this.G.wl(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ix||void 0)||this.G.K("web_player_endscreen_double_log_fix_killswitch"))&&this.G.sb(this.element)};
I2.prototype.onClick=function(a){g.xJ(a,this.G,this.j,this.suggestion.sessionData||void 0)&&this.select()};
I2.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.tt(a)||(this.select(),g.rt(a))}};g.w(K2,g.V);g.h=K2.prototype;g.h.EA=function(a){this.suggestion!==a&&(this.suggestion=a,H2(this.j,a),this.playButton.Ha("url",this.suggestion.mm()),N2(this))};
g.h.Xi=function(){return 0<this.u};
g.h.Uv=function(){this.Xi()||(this.u=Date.now(),J2(this),JXa(this.G,M2(this)),g.N(this.G.getRootNode(),"countdown-running",this.Xi()))};
g.h.Bs=function(){this.Co();J2(this);var a=this.j.ya("ytp-autonav-endscreen-upnext-header");a&&g.Ng(a,"Nast\u0119pny")};
g.h.Co=function(){this.Xi()&&(this.C.stop(),this.u=0)};
g.h.select=function(a){this.G.nextVideo(!1,void 0===a?!1:a);this.Co()};
g.h.EL=function(a){g.xJ(a,this.G)&&(a.currentTarget===this.playButton.element?this.G.sb(this.playButton.element):a.currentTarget===this.j.ya("ytp-autonav-endscreen-link-container")&&(a=this.j.ya("ytp-autonav-endscreen-link-container"),this.G.Va(a,!0),this.G.sb(a)),this.select())};
g.h.GU=function(){this.G.sb(this.cancelButton.element);g.FI(this.G,!0);this.D&&this.G.Ma("innertubeCommand",this.D)};
g.h.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.wS)?void 0:c.command};
g.h.DL=function(){var a=this.G.We();this.I&&this.ob!==a&&g.yG(this,a);N2(this);this.G.Va(this.element,a);this.G.Va(this.cancelButton.element,a);this.G.Va(this.j.ya("ytp-autonav-endscreen-link-container"),a);this.G.Va(this.playButton.element,a)};
g.h.jg=function(a){return 400>a.width||459>a.height};g.w(O2,g.V);g.h=O2.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.nx=function(){return!1};
g.h.We=function(){return!1};
g.h.FO=function(){return!1};g.w(P2,g.V);g.h=P2.prototype;g.h.aB=function(){this.notification&&(this.C.stop(),this.xc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.h.EA=function(a){this.suggestion=a;H2(this,a,"hqdefault.jpg")};
g.h.FL=function(){g.yG(this,this.api.We());this.api.Va(this.element,this.api.We());this.api.Va(this.ya("ytp-upnext-autoplay-icon"),this.api.We());this.cancelButton&&this.api.Va(this.cancelButton.element,this.api.We())};
g.h.CZ=function(){window.focus();this.aB()};
g.h.Uv=function(a){var b=this;this.Xi()||(g.It("a11y-announce","Nast\u0119pny "+this.suggestion.title),this.u=(0,g.Q)(),this.j=new g.K(function(){Q2(b,a)},25),Q2(this,a),JXa(this.api,KXa(this,a)));
g.jo(this.element,"ytp-upnext-autoplay-paused")};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.Xi=function(){return!!this.j};
g.h.Bs=function(){this.Co();this.u=(0,g.Q)();Q2(this);g.ho(this.element,"ytp-upnext-autoplay-paused")};
g.h.Co=function(){this.Xi()&&(this.j.dispose(),this.j=null)};
g.h.select=function(a){a=void 0===a?!1:a;if(this.api.S().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.aB(),this.notification=new Notification("Nast\u0119pny",{body:this.suggestion.title,icon:this.suggestion.Bf()}),this.B=this.P(this.notification,"click",this.CZ),this.C.start())}this.Co();this.api.nextVideo(!1,a)};
g.h.IU=function(a){!g.Mg(this.cancelButton.element,g.nt(a))&&g.xJ(a,this.api)&&(this.api.We()&&this.api.sb(this.ya("ytp-upnext-autoplay-icon")),this.select())};
g.h.HU=function(){this.api.We()&&this.cancelButton&&this.api.sb(this.cancelButton.element);g.FI(this.api,!0)};
g.h.tZ=function(a){this.api.getPresentingPlayerType();this.show();this.Uv(a)};
g.h.uZ=function(){this.api.getPresentingPlayerType();this.Co();this.hide()};
g.h.ea=function(){this.Co();this.aB();g.V.prototype.ea.call(this)};g.w(R2,O2);g.h=R2.prototype;g.h.create=function(){O2.prototype.create.call(this);this.C.P(this.player,"appresize",this.Rw);this.C.P(this.player,"onVideoAreaChange",this.Rw);this.C.P(this.player,"videodatachange",this.onVideoDataChange);this.C.P(this.player,"autonavchange",this.GL);this.C.P(this.player,"autonavcancel",this.JU);this.onVideoDataChange()};
g.h.show=function(){O2.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.FI(this.player,!1);g.LI(this.player)&&this.nx()&&!this.B?(S2(this),2===this.videoData.autonavState?this.player.S().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Uv():3===this.videoData.autonavState&&this.j.Bs()):(g.FI(this.player,!0),S2(this));this.Rw()};
g.h.hide=function(){O2.prototype.hide.call(this);this.j.Bs();S2(this)};
g.h.Rw=function(){var a=this.player.Ej(!0,this.player.isFullscreen());S2(this);N2(this.u);g.N(this.element,"ytp-autonav-cancelled-small-mode",this.jg(a));g.N(this.element,"ytp-autonav-cancelled-tiny-mode",this.gC(a));g.N(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.bl(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.N(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.h.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.j.EA(a[0]);this.j!==this.u&&this.u.EA(a[0]);for(var b=0;b<OXa.length;++b){var c=OXa[b];if(a&&a[c]){this.videos[b]=new I2(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,H2(d,c));g.I(this,this.videos[b]);this.videos[b].xa(this.J.element)}}}this.Rw()}};
g.h.GL=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Co(),this.ob&&this.Rw()):(this.I=!0,this.We()&&(2===a?this.j.Uv():3===a&&this.j.Bs()))};
g.h.JU=function(a){a?this.GL(1):(this.B=null,this.I=!1)};
g.h.nx=function(){return 1!==this.videoData.autonavState};
g.h.jg=function(a){return(910>a.width||459>a.height)&&!this.gC(a)&&!(400>=a.width||360>=a.height)};
g.h.gC=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.h.We=function(){return this.ob&&g.LI(this.player)&&this.nx()&&!this.B};
var OXa=[1,3,2,4];g.w(T2,O2);T2.prototype.Ea=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.pk;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.w(U2,g.V);U2.prototype.select=function(){(this.api.wl(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ix||void 0)||this.api.K("web_player_endscreen_double_log_fix_killswitch"))&&this.api.sb(this.element)};
U2.prototype.onClick=function(a){g.xJ(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
U2.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.tt(a)||(this.select(),g.rt(a))}};
U2.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.S();this.u=a.D?!1:b.j};g.w(V2,O2);g.h=V2.prototype;g.h.create=function(){O2.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Xm();this.u.P(this.player,"appresize",this.Xm);this.u.P(this.player,"onVideoAreaChange",this.Xm);this.u.P(this.player,"videodatachange",this.onVideoDataChange);this.u.P(this.player,"autonavchange",this.PE);this.u.P(this.player,"autonavcancel",this.KU);a=this.videoData.autonavState;a!==this.N&&this.PE(a);this.u.P(this.element,"transitionend",this.P_)};
g.h.destroy=function(){g.ku(this.u);g.Ee(this.stills);this.stills=[];O2.prototype.destroy.call(this);g.jo(this.element,"ytp-show-tiles");this.I.stop();this.N=this.videoData.autonavState};
g.h.nx=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){O2.prototype.show.call(this);g.jo(this.element,"ytp-show-tiles");this.player.S().isMobile?g.Jn(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.FI(this.player,!1);W2(this)?(X2(this),2===this.videoData.autonavState?this.player.S().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Uv():3===this.videoData.autonavState&&this.j.Bs()):(g.FI(this.player,!0),X2(this))};
g.h.hide=function(){O2.prototype.hide.call(this);this.j.Bs();X2(this)};
g.h.P_=function(a){g.nt(a)===this.element&&this.Xm()};
g.h.Xm=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.ho(this.element,"ytp-endscreen-paginate");var a=this.G.Ej(!0,this.G.isFullscreen()),b=g.AI(this.G);b&&(b=b.Lf()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,q=e/2,t=b<=f-2&&n>=q*m,u=e<=k-2&&n>=p*m;if((p+
1)/q*d/c>c/(p/(q+1)*d)&&u)n-=p*m,e+=2;else if(t)n-=q*m,b+=2;else if(u)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.ll(a,m,n);g.bl(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.j.EA(this.videoData.suggestions[0]);this.j instanceof K2&&N2(this.j);g.N(this.element,"ytp-endscreen-takeover",W2(this));X2(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,p=0,d&&f>=b-2&&k>=e-2?p=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(p=2):p=2),q=g.dg(q+this.B,l),0!==p){t=this.stills[c];t||(t=new U2(this.player),this.stills[c]=t,a.appendChild(t.element));u=Math.floor(n*k/e);var x=Math.floor(m*f/b),y=Math.floor(n*(k+p)/e)-u-4,z=Math.floor(m*(f+p)/b)-x-4;g.hl(t.element,x,u);g.ll(t.element,z,y);g.bl(t.element,"transitionDelay",(k+f)/20+"s");g.N(t.element,"ytp-videowall-still-mini",1===p);g.N(t.element,"ytp-videowall-still-large",
2<p);p=t;q=this.videoData.suggestions[q];p.suggestion!==q&&(p.suggestion=q,t=p.api.S(),u=g.go(p.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",H2(p,q,u),g.aB(t)&&(u=q.mm(),x={},t.ma&&g.pI(x,t.loaderUrl),u=g.Sh(u,g.oI(x,"emb_rel_end")),p.Ha("url",u)),(q=(q=q.sessionData)&&q.itct)&&p.api.il(p.element,q));c++}g.N(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Kg(e.element),g.De(e);this.stills.length=c}};
g.h.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Xm())};
g.h.LU=function(){this.B+=this.stills.length;this.Xm()};
g.h.MU=function(){this.B-=this.stills.length;this.Xm()};
g.h.FO=function(){return this.j.Xi()};
g.h.PE=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Co(),this.ob&&this.Xm()):(this.D=!0,this.ob&&W2(this)&&(2===a?this.j.Uv():3===a&&this.j.Bs()))};
g.h.KU=function(a){if(a){for(a=0;a<this.stills.length;a++)this.G.Va(this.stills[a].element,!0);this.PE(1)}else this.C=null,this.D=!1;this.Xm()};
g.h.We=function(){return this.ob&&W2(this)};g.w(Y2,g.YI);g.h=Y2.prototype;g.h.Qs=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!LXa(this.player)||b;var c=a.Hf||g.lB(a.u),d=this.player.Ox();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.We=function(){return this.endScreen.We()};
g.h.sX=function(){return this.We()?this.endScreen.FO():!1};
g.h.ea=function(){this.player.Ff("endscreen");g.YI.prototype.ea.call(this)};
g.h.load=function(){var a=this.player.getVideoData();var b=a.JQ;if(b&&b.videoId){var c=this.player.ib().Ud.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.aM?a=!1:(this.player.wl(b.videoId,void 0,void 0,!0,!0,b),c&&c.oC("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.YI.prototype.load.call(this),this.endScreen.show())};
g.h.unload=function(){g.YI.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.onCueRangeEnter=function(a){this.Qs()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.onVideoDataChange=function(){NXa(this);this.B&&MXa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new R2(this.player):this.endScreen=new V2(this.player),g.I(this,this.endScreen),g.KI(this.player,this.endScreen.element,4))};g.XI("endscreen",Y2);})(_yt_player);
