(function(g){var window=this;'use strict';var DYa=function(a,b){var c=[];return g.es(a,{query:b},function(d){c.push(d.getValue());return d.continue()}).then(function(){return c})},M3=function(a,b){return"getAll"in IDBIndex.prototype?g.Tr(a.j.getAll(b,void 0)):DYa(a,b)},EYa=function(a,b){return g.Zr(a,["captions"],{mode:"readonly",
vc:!0},function(c){return g.moa(c.objectStore("captions"),b)})},FYa=function(a){var b=new g.Lw("und",new g.lz("Default","und",!0));
b.captionTracks=a.captionTracks;return b},GYa=function(a){return new g.Zg(function(b,c){var d=a.length,e=[];
if(d)for(var f=function(n,p){d--;e[n]=p;0==d&&b(e)},k=function(n){c(n)},l=0,m;l<a.length;l++)m=a[l],g.dda(m,g.Sa(f,l),k);
else b(e)})},N3=function(a){this.j=a},O3=function(){N3.apply(this,arguments)},P3=function(){O3.apply(this,arguments)},Q3=function(){O3.apply(this,arguments)},R3=function(){O3.apply(this,arguments)},S3=function(){N3.apply(this,arguments)},T3=function(){O3.apply(this,arguments)},U3=function(){O3.apply(this,arguments)},V3=function(){O3.apply(this,arguments)},W3=function(){O3.apply(this,arguments)},X3=function(){O3.apply(this,arguments)},Y3=function(){O3.apply(this,arguments)},Z3=function(){O3.apply(this,
arguments)},$3=function(){N3.apply(this,arguments)},a4=function(){O3.apply(this,arguments)},b4=function(){O3.apply(this,arguments)},c4=function(){O3.apply(this,arguments)},d4=function(){O3.apply(this,arguments)},e4=function(){O3.apply(this,arguments)},f4=function(){O3.apply(this,arguments)},g4=function(){O3.apply(this,arguments)},h4=function(){N3.apply(this,arguments)},i4=function(){O3.apply(this,arguments)},j4=function(){O3.apply(this,arguments)},k4=function(){O3.apply(this,arguments)},l4=function(){O3.apply(this,
arguments)},m4=function(){O3.apply(this,arguments)},n4=function(){O3.apply(this,arguments)},o4=function(){O3.apply(this,arguments)},p4=function(){O3.apply(this,arguments)},q4=function(){O3.apply(this,arguments)},r4=function(){O3.apply(this,arguments)},s4=function(){O3.apply(this,arguments)},t4=function(){O3.apply(this,arguments)},u4=function(){O3.apply(this,arguments)},v4=function(){O3.apply(this,arguments)},w4=function(){O3.apply(this,arguments)},x4=function(){O3.apply(this,arguments)},y4=function(){O3.apply(this,
arguments)},z4=function(){O3.apply(this,arguments)},A4=function(){O3.apply(this,arguments)},B4=function(){O3.apply(this,arguments)},C4=function(){O3.apply(this,arguments)},D4=function(){O3.apply(this,arguments)},E4=function(){O3.apply(this,arguments)},F4=function(){O3.apply(this,arguments)},G4=function(){O3.apply(this,arguments)},H4=function(){O3.apply(this,arguments)},I4=function(){O3.apply(this,arguments)},J4=function(){O3.apply(this,arguments)},K4=function(){O3.apply(this,arguments)},L4=function(){O3.apply(this,
arguments)},M4=function(){O3.apply(this,arguments)},N4=function(){O3.apply(this,arguments)},O4=function(a){a=a.key||a.id;
if(!a)throw Error("Entity key is missing");return a},HYa=function(){if(P4)return P4();
var a={};P4=g.Ds("PersistentEntityStoreDb",{rs:(a.EntityStore={Ro:1},a.EntityAssociationStore={Ro:2},a),Hz:!1,upgrade:function(b,c){c(1)&&g.bs(g.Xr(b,"EntityStore",{keyPath:"key"}),"entityType","entityType");c(2)&&(b=g.Xr(b,"EntityAssociationStore",{keyPath:["parentEntityKey","childEntityKey"]}),g.bs(b,"byParentEntityKey","parentEntityKey"),g.bs(b,"byChildEntityKey","childEntityKey"))},
version:3});return P4()},IYa=function(a){return g.hs(HYa(),a)},Q4=function(a,b){b=void 0===b?{}:b;
g.Dr.call(this,g.uUa[a],Object.assign({},{name:"PESEncoderError",type:a},b));this.type=a;this.level="WARNING";Object.setPrototypeOf(this,Q4.prototype)},JYa=function(a){return new Q4("WRONG_DATA_TYPE",{kW:a})},KYa=function(a){return a instanceof Error?new Q4("UNKNOWN_ENCODE_ERROR",{originalMessage:a.message}):new Q4("UNKNOWN_ENCODE_ERROR")},LYa=function(a){return a instanceof Error?new Q4("UNKNOWN_DECODE_ERROR",{originalMessage:a.message}):new Q4("UNKNOWN_DECODE_ERROR")},MYa=function(a,b){a=a instanceof
Q4?a:b(a);
g.R(a);throw a;},NYa=function(){},OYa=function(a,b,c){try{return a.B(b,c)}catch(d){MYa(d,KYa)}},R4=function(a){a=(new TextEncoder).encode(a).subarray(0,16);
var b=new Uint8Array(16);b.set(a);return b},S4=function(a){this.j=a},QYa=function(a){var b=PYa[a];
if(b)return b;g.Eu(new g.Dr("Entity model not found.",{entityType:a}))},RYa=function(a,b){this.j=a;
this.u=b;this.B={}},U4=function(a,b){a:{a=T4(a.u,b.version);
try{var c=a.u(b.data,b.key);break a}catch(d){MYa(d,LYa)}c=void 0}return c},V4=function(a,b,c){return a.j.objectStore("EntityStore").get(b).then(function(d){if(d){if(c&&d.entityType!==c)throw Error("Incorrect entity type");
return U4(a,d)}})},W4=function(a,b,c){return c?(c=c.map(function(d){return V4(a,d,b)}),g.Rr.all(c)):M3(a.j.objectStore("EntityStore").index("entityType"),IDBKeyRange.only(b)).then(function(d){return d.map(function(e){return U4(a,e)})})},Y4=function(a,b,c){var d=O4(b),e=T4(a.u,1),f=Object.assign({},b);
return a.j.objectStore("EntityStore").get(d).then(function(k){if(k){if(k.entityType!==c)throw Error("Incorrect entity type");f.entityMetadata||(k=U4(a,k),f.entityMetadata=k.entityMetadata)}}).then(function(){var k={key:d,
entityType:c,data:OYa(e,f,d),version:1};return g.Rr.all([g.$r(a.j.objectStore("EntityStore"),k),SYa(a,f,c)])}).then(function(){X4(a,d,c);
return d})},Z4=function(a,b,c){b=b.map(function(d){return Y4(a,d,c)});
return g.Rr.all(b)},$4=function(a,b,c){if(null==c?0:c.WA){var d=new Set;
return TYa(a,b,d).then(function(){for(var f=[],k=g.r(d),l=k.next();!l.done;l=k.next())f.push($4(a,l.value));return g.Rr.all(f).then(function(){})})}var e=g.IC(b).entityType;
return g.Rr.all([a.j.objectStore("EntityStore").delete(b),a5(a,b)]).then(function(){X4(a,b,e)})},UYa=function(a,b){return g.es(a.j.objectStore("EntityStore").index("entityType"),{query:IDBKeyRange.only(b)},function(c){return g.Rr.all([c.delete(),
a5(a,c.MB())]).then(function(){X4(a,c.MB(),b);return c.continue()})})},VYa=function(a,b,c,d){var e=T4(a.u,1);
return V4(a,b,d).then(function(f){if(f){f=g.sC(f,c);var k={key:b,entityType:d,data:OYa(e,f,b),version:1};return g.Rr.all([g.$r(a.j.objectStore("EntityStore"),k),SYa(a,f,d)])}}).then(function(){X4(a,b,d);
return b})},X4=function(a,b,c){var d=a.B[c];
d||(d=new Set,a.B[c]=d);d.add(b)},WYa=function(a,b,c){var d=O4(b);
c=QYa(c);if(!c)return g.Rr.resolve([]);c=new c(b);a=a.j.objectStore("EntityAssociationStore");b=[];c=g.r(c.u());for(var e=c.next();!e.done;e=c.next())b.push(g.$r(a,{parentEntityKey:d,childEntityKey:e.value}));return g.Rr.all(b).then(function(f){return f.map(function(k){return k[1]})})},a5=function(a,b){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b))},SYa=function(a,b,c){var d=O4(b);
return a5(a,d).then(function(){return WYa(a,b,c)})},TYa=function(a,b,c){if(c.has(b))return g.Rr.resolve(void 0);
c.add(b);return XYa(a,b).then(function(d){return a.j.objectStore("EntityAssociationStore").index("byParentEntityKey").delete(IDBKeyRange.only(b)).then(function(){return d})}).then(function(d){var e=g.Rr.resolve(void 0),f={};
d=g.r(d);for(var k=d.next();!k.done;f={YD:f.YD},k=d.next())f.YD=k.value,e=e.then(function(l){return function(){return TYa(a,l.YD,c)}}(f));
return e}).then(function(){})},XYa=function(a,b){var c=a.j.objectStore("EntityAssociationStore");
return M3(c.index("byParentEntityKey"),IDBKeyRange.only(b)).then(function(d){var e=[];d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,e.push(M3(c.index("byChildEntityKey"),f.childEntityKey));return g.Rr.all(e)}).then(function(d){var e=[];
d=g.r(d);for(var f=d.next();!f.done;f=d.next())f=f.value,1===f.length&&e.push(f[0].childEntityKey);return e})},b5=function(){},YYa=function(){this.j={};
this.j[0]=new b5;if(!g.P("aes_pes_encoder_killswitch")){var a=this.j;try{var b=g.Er();var c=R4(b);var d=new S4(new g.CA(c),new g.BA(c))}catch(e){throw a=e instanceof Error?new Q4("KEY_CREATION_FAILED",{originalMessage:e.message}):new Q4("KEY_CREATION_FAILED"),g.R(a),a;}a[1]=d}},T4=function(a,b){b=void 0===b?0:b;
a=a.j[b];if(!a)throw b=new Q4("INVALID_ENCODER_VERSION",{kW:b}),g.R(b),b;return a},c5=function(a,b){g.G.call(this);
this.token=a;this.u=b;this.j=[];a=new g.C.BroadcastChannel("PERSISTENT_ENTITY_STORE_SYNC:"+g.Er());a.onmessage=this.B.bind(this);this.channel=a},d5=function(a,b,c){var d,e,f,k;
return g.B(function(l){if(1==l.j)return g.A(l,IYa(a.token),2);if(3!=l.j)return d=l.u,g.A(l,g.Zr(d,["EntityStore","EntityAssociationStore"],b,function(m){e=new RYa(m,a.u);return c(e)}),3);
f=l.u;e&&(k=e.B,0<Object.keys(k).length&&(a.channel.postMessage(k),ZYa(a,k)));return l.return(f)})},e5=function(a,b){a.j.push(b);
return function(){var c=a.j.indexOf(b);0<=c&&a.j.splice(c,1)}},f5=function(a,b,c){return d5(a,{mode:"readwrite",
vc:!0},function(d){return Y4(d,b,c)})},$Ya=function(a,b){return d5(a,{mode:"readwrite",
vc:!0},function(c){return Z4(c,b,"offlineOrchestrationActionWrapperEntity")})},aZa=function(a,b){return d5(a,{mode:"readwrite",
vc:!0},function(c){return $4(c,b)})},g5=function(a,b,c){return d5(a,{mode:"readonly",
vc:!0},function(d){return V4(d,b,c)})},h5=function(a,b,c){return d5(a,{mode:"readonly",
vc:!0},function(d){return W4(d,b,c)})},ZYa=function(a,b){a=g.r(a.j);
for(var c=a.next();!c.done;c=a.next())c=c.value,c(b)},bZa=function(){var a,b,c;
return g.B(function(d){if(1==d.j)return g.ua(d,2),g.A(d,g.os(),4);if(2!=d.j){a=d.u;if(!a||!g.Fr()||"undefined"===typeof g.C.BroadcastChannel)return d.return();b=new YYa;return d.return(new c5(a,b))}c=g.wa(d);c instanceof Error&&g.R(c);return d.return()})},j5=function(){i5||(i5=bZa());
return i5},cZa=function(a){var b;
a=null==(b=a.options)?void 0:b.persistenceOption;return"ENTITY_PERSISTENCE_OPTION_PERSIST"===a||"ENTITY_PERSISTENCE_OPTION_INMEMORY_AND_PERSIST"===a},dZa=function(a){var b;
return g.B(function(c){return 1==c.j?g.A(c,j5(),2):(b=c.u)?g.A(c,d5(b,"readwrite",function(d){for(var e={},f={},k=g.r(a),l=k.next();!l.done;f={ih:f.ih,At:f.At},l=k.next())f.ih=l.value,f.ih.entityKey&&cZa(f.ih)&&(f.At=g.Qe(f.ih.payload),l=void 0,"ENTITY_MUTATION_TYPE_REPLACE"===f.ih.type&&(l=function(m){return function(){return Y4(d,m.ih.payload[m.At],m.At)}}(f)),"ENTITY_MUTATION_TYPE_DELETE"===f.ih.type&&(l=function(m){return function(){return $4(d,m.ih.entityKey)}}(f)),"ENTITY_MUTATION_TYPE_UPDATE"===
f.ih.type&&(l=function(m){return function(){return VYa(d,m.ih.entityKey,m.ih.payload[m.At],m.At)}}(f)),l&&(e[f.ih.entityKey]=e[f.ih.entityKey]?e[f.ih.entityKey].then(l):l()));
return g.Rr.all(Object.values(e))}),0):c.return()})},eZa=function(a){var b;
return g.B(function(c){if(1==c.j){b=a.mutations;if(!b||0>=b.length)return c.return();if(g.yD){var d={type:"ENTITY_LOADED"};void 0!==b&&(d.payload=b);g.yD.dispatch(d)}return g.A(c,dZa(b),2)}b.length=0;g.sa(c)})},fZa=function(a){return void 0!==a},gZa=function(a){var b=g.TC();
b=Object.assign({},b);a=Object.assign({},a);for(var c in b)a[c]?(4!==b[c]&&(b[c]=a[c]),delete a[c]):2!==b[c]&&(b[c]=4);Object.assign(b,a);g.twa(b);JSON.stringify(b);return b},hZa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,g.os(),2);if(3!=d.j)return(b=d.u)?g.A(d,g.WC(b),3):d.return();c=d.u;return d.return(g.Zr(c,["index","media","captions"],{mode:"readwrite",vc:!0},function(e){var f=IDBKeyRange.bound(a+"|",a+"~");e=[e.objectStore("index").delete(f),e.objectStore("media").delete(f),e.objectStore("captions").delete(f)];return g.Rr.all(e).then(function(){})}))})},iZa=function(){var a,b;
return g.B(function(c){if(1==c.j)return g.A(c,g.os(),2);if(3!=c.j){a=c.u;if(!a)throw g.Pr("rvdfd");return g.A(c,g.WC(a),3)}b=c.u;return c.return(g.Zr(b,["index","media"],{mode:"readwrite",vc:!0},function(d){var e={};return g.cs(d.objectStore("index"),{},function(f){var k=f.getKey().match(/^([\w\-_]+)\|(a|v)$/),l=g.Rr.resolve(void 0);if(k){var m=k[1];k=k[2];e[m]=e[m]||{};var n;e[m][k]=g.ywa(null==(n=f.getValue())?void 0:n.fmts)}else l=f.delete().then(function(){});
return g.Rr.all([f.continue(),l]).then(function(p){return g.r(p).next().value})}).then(function(){for(var f={},k=g.r(Object.keys(e)),l=k.next();!l.done;l=k.next()){l=l.value;
var m=e[l].v;f[l]=e[l].a&&m?1:2}var n=gZa(f);return g.poa(d.objectStore("media"),{},function(p){var q=p.getKey().match(g.Cwa);q&&f[q[1]]||d.objectStore("media").delete(p.getKey());return p.continue()}).then(function(){return n})})}))})},jZa=function(a,b){var c,d;
return g.B(function(e){if(1==e.j)return g.A(e,g.os(),2);if(3!=e.j){c=e.u;if(!c)throw g.Pr("wct");return g.A(e,g.WC(c),3)}d=e.u;return g.A(e,g.Zr(d,["captions"],{mode:"readwrite",vc:!0},function(f){var k=[];f=f.objectStore("captions");for(var l=0;l<b.length;l++){var m=g.$r(f,b[l],a+"|"+b[l].metadata.vss_id);k.push(m)}return g.Rr.all(k)}),0)})},kZa=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return b=IDBKeyRange.bound(a+"|",a+"~"),g.A(e,g.os(),2);if(3!=e.j){c=e.u;if(!c)throw g.Pr("gactfv");return g.A(e,g.WC(c),3)}d=e.u;return e.return(EYa(d,b))})},lZa=function(a){return g.B(function(b){g.VC(a,0);
return b.return(hZa(a))})},mZa=function(a){return{context:g.VF(),
videoIds:a}},nZa=function(a){return{context:g.VF(),
playlistIds:a}},k5=function(a,b,c){g.Eu(new g.Dr("Woffle: "+a,c?{cotn:c}:""));
b instanceof Error&&g.Eu(b)},oZa=function(a){var b,c,d,e,f,k,l,m,n,p,q,t,u,x,y,z,D;
return g.B(function(H){if(1==H.j)return g.A(H,d5(a,{mode:"readonly",vc:!0},function(J){return W4(J,"playbackData").then(function(L){var ba=L.map(function(ta){return ta.transfer}).filter(function(ta){return!!ta}),M=L.map(function(ta){return ta.offlineVideoPolicy}).filter(function(ta){return!!ta});
ba=W4(J,"transfer",ba);M=W4(J,"offlineVideoPolicy",M);return g.Rr.all([ba,M]).then(function(ta){var Y=g.r(ta);ta=Y.next().value;Y=Y.next().value;return[L,ta,Y]})})}),2);
b=H.u;c=g.r(b);d=c.next().value;e=c.next().value;f=c.next().value;k=d;l=e;m=f;n={};p={};q=g.r(l);for(t=q.next();!t.done;t=q.next())(u=t.value)&&(n[u.key]=u);x=g.r(m);for(y=x.next();!y.done;y=x.next())(z=y.value)&&(p[z.key]=z);D=k.map(function(J){var L=n[J.transfer],ba=p[J.offlineVideoPolicy];J=g.IC(ba.key).entityId;if("OFFLINE_VIDEO_POLICY_ACTION_DISABLE"===ba.action){var M="OFFLINE_VIDEO_STATE_DISABLED";ba.expirationTimestamp&&Number(ba.expirationTimestamp)<Date.now()/1E3&&(M="OFFLINE_VIDEO_STATE_EXPIRED");
ba=M}else if("OFFLINE_VIDEO_POLICY_ACTION_DOWNLOAD_FAILED"===ba.action)ba="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";else{switch(null==L?void 0:L.transferState){case "TRANSFER_STATE_TRANSFER_IN_QUEUE":M="OFFLINE_VIDEO_STATE_PENDING";break;case "TRANSFER_STATE_TRANSFERRING":M="OFFLINE_VIDEO_STATE_TRANSFERRING";break;case "TRANSFER_STATE_PAUSED_BY_USER":M="OFFLINE_VIDEO_STATE_PAUSED_TRANSFER";break;case "TRANSFER_STATE_FAILED":M="OFFLINE_VIDEO_STATE_OFFLINE_FAILED";break;case "TRANSFER_STATE_COMPLETE":M=
"OFFLINE_VIDEO_STATE_PLAYABLE";break;case "TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH":M="OFFLINE_VIDEO_STATE_STREAMS_OUT_OF_DATE";break;default:M="OFFLINE_VIDEO_STATE_UNKNOWN"}if("OFFLINE_VIDEO_STATE_OFFLINE_FAILED"===M)switch(null==L?void 0:L.failureReason){case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":M="OFFLINE_VIDEO_STATE_OUT_OF_STORAGE_ERROR";break;case "TRANSFER_FAILURE_REASON_STREAM_MISSING":M="OFFLINE_VIDEO_STATE_STREAMS_MISSING";
break;case "TRANSFER_FAILURE_REASON_NETWORK":case "TRANSFER_FAILURE_REASON_NETWORK_LOST":M="OFFLINE_VIDEO_STATE_NETWORK_ERROR"}ba=M}J={id:J,videoState:ba};if(null==L?0:L.cotn)J.cotn=L.cotn;if(null==L?0:L.maximumDownloadQuality)J.selectedVideoQuality=null==L?void 0:L.maximumDownloadQuality;return J});
return H.return({offlineVideos:D})})},pZa=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,oZa(a),2);b=c.u;g.yr("offlineStateSnapshot",b);g.sa(c)})},l5=function(a){g.G.call(this);
this.api=a;"undefined"!==typeof g.C.BroadcastChannel&&(this.j=new g.C.BroadcastChannel("PLAYER_OFFLINE_ERROR_SYNC:"+g.Er()),this.j.onmessage=this.B.bind(this),this.u=new g.C.BroadcastChannel("PLAYER_OFFLINE_PAUSE_SYNC:"+g.Er()),this.u.onmessage=this.C.bind(this))},m5=function(a,b){a.api.Ma("onOfflineOperationFailure",b);
var c;null==(c=a.j)||c.postMessage(b)},qZa=function(){this.locks=navigator.locks},rZa=function(){try{var a=g.Ka("ytglobal.locks_");
if(a)return a;var b;if(b=navigator){var c=navigator;b="locks"in c&&!!c.locks}if(b)return g.C.localStorage&&g.C.localStorage.getItem("noop"),a=new qZa,g.Ja("ytglobal.locks_",a),a}catch(d){}},tZa=function(a,b,c,d){var e=this;
this.N=a;this.V=b;this.visibility=c;this.K=d;this.C=this.I=this.D=this.u=this.j=!1;this.J=new g.K(function(){sZa(e)});
this.visibility.subscribe("visibilitystatechange",function(){e.wf()})},uZa=function(a){if(!a.u&&!a.j){var b=rZa();
if(b){a.u=!0;var c=g.Er("OfflineLockManager");b.request("woffle_orchestration_leader:"+c,{},function(){var d,e,f,k;return g.B(function(l){switch(l.j){case 1:return g.ua(l,2),a.B=new g.ti,a.j=!0,a.u=!1,g.A(l,a.N(),4);case 4:return g.A(l,a.B.promise,5);case 5:g.va(l,0);break;case 2:d=g.wa(l),(null==(f=(e=a).K)?0:f.call(e,"wo_relinquish_leadership_on_lock_request_error"))||sZa(a),d instanceof Error&&(k=d,k.args=[{name:"WoLockManagerError",OC:d.name}],g.R(k)),g.sa(l)}})})}}},vZa=function(a){a.j&&(a.C=
!0,n5(a))},wZa=function(a,b){a.j&&(a.D=b,n5(a))},xZa=function(a,b){a.j&&(a.I=b,n5(a))},n5=function(a){a.I&&a.D&&a.C&&a.visibility.isBackground()?g.In(a.J,6E4):a.J.stop()},sZa=function(a){a.B&&a.B.resolve();
a.j=!1;a.u=!1;a.V()},o5=function(a,b){var c=b.jj;
a.encryptedVideoId=b.videoId;a.cotn=c.cotn;a.offlineabilityFormatType=c.maximumDownloadQuality;var d;a.isRefresh=null!=(d=c.isRefresh)?d:!1;var e;a.softErrorCount=null!=(e=c.transferRetryCount)?e:0;g.yr("offlineTransferStatusChanged",a)},yZa=function(a,b,c,d){b=Math.floor(b/1024).toFixed();
o5({transferStatusType:"TRANSFER_STATUS_TYPE_PROCESSING",statusType:"OFFLINING_STARTED",transferFirstStarted:!!d,alreadyDownloadedKbytes:b,totalFetchedKbytes:b,totalContentKbytes:Math.floor(c/1024).toFixed()},a)},zZa=function(a){o5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_USER_PAUSE",
statusType:"SUSPENDED"},a)},AZa=function(a){switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":return"OFFLINE_DATABASE_ERROR";
case "TRANSFER_FAILURE_REASON_PLAYABILITY":return"NOT_PLAYABLE";case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":return"TOO_MANY_RETRIES";case "TRANSFER_FAILURE_REASON_INTERNAL":return"OFFLINE_DOWNLOAD_CONTROLLER_ERROR";case "TRANSFER_FAILURE_REASON_STREAM_MISSING":return"STREAM_VERIFICATION_FAILED";case "TRANSFER_FAILURE_REASON_SERVER":case "TRANSFER_FAILURE_REASON_SERVER_PROPERTY_MISSING":return"OFFLINE_REQUEST_FAILURE";case "TRANSFER_FAILURE_REASON_NETWORK":return"OFFLINE_NETWORK_ERROR";default:return"UNKNOWN_FAILURE_REASON"}},
p5=function(){},q5=function(){},r5=function(a){if(a.includes(":"))throw Error("Invalid user cache name: "+a);
return a+":"+g.Er("CacheStorage get")},BZa=function(){return g.B(function(a){if(void 0!==s5)return a.return(s5);
s5=new Promise(function(b){var c;return g.B(function(d){switch(d.j){case 1:return g.ua(d,2),g.A(d,t5.open("test-only"),4);case 4:return g.A(d,t5.delete("test-only"),5);case 5:g.va(d,3);break;case 2:if(c=g.wa(d),c instanceof Error&&"SecurityError"===c.name)return b(!1),d.return();case 3:b("caches"in window),g.sa(d)}})});
return a.return(s5)})},v5=function(){return g.B(function(a){if(1==a.j)return g.A(a,BZa(),2);
if(!a.u)return a.return(void 0);u5||(u5=new q5);return a.return(u5)})},CZa=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,v5(),2):(a=b.u)?b.return(a.delete("yt-player-local-img")):b.return(!0)})},DZa=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,v5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,Promise.all(a.map(function(e){return c.delete(e)})),0)})},w5=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,v5(),2);if(3!=d.j){b=d.u;if(!b)throw Error("Cache API not supported");return a.length?g.A(d,b.open("yt-player-local-img"),3):d.return()}c=d.u;return g.A(d,c.addAll(a),0)})},x5=function(a){var b,c,d;
return 0<(null!=(d=null==(b=a.actionMetadata)?void 0:null==(c=b.retryScheduleIntervalsInSeconds)?void 0:c.length)?d:0)},y5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===a.actionType&&!!a.entityKey},z5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"===a.actionType&&!!a.entityKey},A5=function(a){return"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE"===a.actionType&&!!a.entityKey},D5=function(a,b,c,d){var e,f,k,l,m,n,p,q,t,u,x,y,z,D,H,J,L,ba,M,ta,Y,Aa,Ia,fb,Eb,Hc,Ab,Yc;
return g.B(function(gb){switch(gb.j){case 1:return e=g.JC(a,"ytMainVideoEntity"),f=g.JC(a,"mainVideoEntity"),k=g.JC(a,"ytMainChannelEntity"),l=g.JC(a,"transfer"),g.A(gb,d5(b,{mode:"readonly",vc:!0},function(Pb){return g.Rr.all([V4(Pb,e,"ytMainVideoEntity"),V4(Pb,f,"mainVideoEntity"),V4(Pb,k,"ytMainChannelEntity"),V4(Pb,l,"transfer"),W4(Pb,"ytMainChannelEntity"),W4(Pb,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:m=gb.u;n=g.r(m);p=n.next().value;q=n.next().value;t=n.next().value;u=n.next().value;x=n.next().value;y=n.next().value;z=p;D=q;H=t;J=u;L=x;ba=y;if(!(z||D||H)){gb.Ra(3);break}M=z?B5(z.thumbnail):D?B5(D.thumbnail):[];if(!H){ta=[];gb.Ra(4);break}return g.A(gb,EZa(H,L),5);case 5:ta=gb.u;case 4:return Y=ta,g.A(gb,DZa(M.concat(Y)),3);case 3:Aa=[];Ia=g.JC(a,"ytMainDownloadedVideoEntity");fb=g.JC(a,"mainVideoEntity");Eb=g.r(ba);for(Hc=Eb.next();!Hc.done;Hc=Eb.next())Ab=Hc.value,Yc=g.IC(Ab.key).entityId,
Yc!==a||C5(c,Ab.actionProto)||Aa.push(Ab.key);return g.A(gb,d5(b,{mode:"readwrite",vc:!0},function(Pb){var yd=Aa.map(function(of){return $4(Pb,of)});
yd.push($4(Pb,Ia,{WA:!0}));yd.push($4(Pb,fb,{WA:!0}));return g.Rr.all(yd)}),7);
case 7:FZa(J),m5(d,{entityKey:Ia,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),m5(d,{entityKey:fb,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"}),g.sa(gb)}})},IZa=function(a,b,c,d){var e,f,k,l,m,n,p,q,t,u,x,y,z,D,H,J,L,ba,M,ta,Y,Aa,Ia,fb,Eb,Hc,Ab,Yc;
return g.B(function(gb){switch(gb.j){case 1:return e=g.JC(a,"mainPlaylistEntity"),f=g.JC(a,"ytMainChannelEntity"),g.A(gb,d5(b,{mode:"readonly",vc:!0},function(Pb){return g.Rr.all([V4(Pb,e,"mainPlaylistEntity"),V4(Pb,f,"ytMainChannelEntity"),W4(Pb,"mainPlaylistEntity"),W4(Pb,"ytMainChannelEntity"),W4(Pb,"offlineOrchestrationActionWrapperEntity")])}),2);
case 2:k=gb.u;l=g.r(k);m=l.next().value;n=l.next().value;p=l.next().value;q=l.next().value;t=l.next().value;u=m;x=n;y=p;z=q;D=t;if(!u&&!x){gb.Ra(3);break}H=u?GZa(u):[];if(!x){J=[];gb.Ra(4);break}return g.A(gb,EZa(x,z),5);case 5:J=gb.u;case 4:return L=J,g.A(gb,DZa(H.concat(L)),3);case 3:if(!u){gb.Ra(7);break}return g.A(gb,HZa(u,y),8);case 8:ba=gb.u;if(!ba){gb.Ra(7);break}M=g.r(ba);ta=M.next();case 10:if(ta.done){gb.Ra(7);break}Y=ta.value;Aa=g.IC(Y).entityId;return g.A(gb,D5(Aa,b,c,d),11);case 11:ta=
M.next();gb.Ra(10);break;case 7:Ia=[];fb=g.r(D);for(Eb=fb.next();!Eb.done;Eb=fb.next())Hc=Eb.value,Ab=g.IC(Hc.key).entityId,Ab!==a||C5(c,Hc.actionProto)||Ia.push(Hc.key);Yc=g.JC(a,"mainPlaylistEntity");return g.A(gb,d5(b,{mode:"readwrite",vc:!0},function(Pb){var yd=Ia.map(function(of){return $4(Pb,of)});
yd.push($4(Pb,Yc,{WA:!0}));return g.Rr.all(yd)}),0)}})},E5=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j)return g.A(n,d5(a,{mode:"readwrite",vc:!0},function(p){var q=W4(p,"transfer"),t=W4(p,"offlineOrchestrationActionWrapperEntity");return g.Rr.all([q,t]).then(function(u){u=g.r(u);var x=u.next().value,y=u.next().value;u=JZa.map(function(L){return UYa(p,L)});
y=g.r(y);for(var z=y.next();!z.done;z=y.next()){z=z.value;var D=g.IC(z.actionProto.entityKey).entityType,H="ytMainDownloadedVideoEntity"===D;D="mainVideoEntity"===D;var J="OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD"===z.actionProto.actionType;C5(b,z.actionProto)||H&&(!H||J)&&D&&(!D||J)||u.push($4(p,z.key,{WA:!0}))}return g.Rr.all(u).then(function(){return x})})}),2);
d=n.u;e=g.r(d);for(f=e.next();!f.done;f=e.next())k=f.value,FZa(k),l=g.IC(k.key).entityId,m=g.JC(l,"ytMainDownloadedVideoEntity"),m5(c,{entityKey:m,failureReason:"OFFLINE_OPERATION_FAILURE_REASON_VIDEO_DELETED"});return g.A(n,CZa(),0)})},C5=function(a,b){return a.actionType===b.actionType&&a.entityKey===b.entityKey},FZa=function(a){if(a&&"TRANSFER_STATE_COMPLETE"!==a.transferState&&"TRANSFER_STATE_FAILED"!==a.transferState){var b=g.IC(a.key).entityId;
o5({transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_BY_USER",statusType:"CANCELLED"},{videoId:b,jj:a})}},B5=function(a){if(!a||!a.thumbnails)return[];
var b=[];a=g.r(a.thumbnails);for(var c=a.next();!c.done;c=a.next())c=c.value,c.url&&b.push(c.url);return b},GZa=function(a,b){var c=[];
if(a.thumbnailStyleData){a=g.r(a.thumbnailStyleData);for(var d=a.next();!d.done;d=a.next()){var e=void 0,f=void 0,k=void 0;c=c.concat(B5(null==(e=d.value)?void 0:null==(f=e.value)?void 0:null==(k=f.collageThumbnail)?void 0:k.coverThumbnail))}}b=B5(b);return c.concat(b)},HZa=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,u;
return g.B(function(x){c=[];if(a.videos){d=g.r(a.videos);for(e=d.next();!e.done;e=d.next())f=e.value,c.push(f);k=g.r(b);for(l=k.next();!l.done;l=k.next())if(m=l.value,m.key!==a.key&&(n=m.videos))for(p=g.r(n),q=p.next();!q.done;q=p.next())t=q.value,u=c.indexOf(t),-1!==u&&c.splice(u,1)}return x.return(c)})},EZa=function(a,b){var c,d,e,f,k,l,m,n;
return g.B(function(p){c=B5(a.avatar);d=g.r(b);for(e=d.next();!e.done;e=d.next())if(f=e.value,f.id!==a.id)for(k=g.r(B5(f.avatar)),l=k.next();!l.done;l=k.next())m=l.value,n=c.indexOf(m),-1!==n&&c.splice(n,1);return p.return(c)})},F5=function(a){this.j=a},KZa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=new Map,d=g.r(b),e=d.next();case 2:if(e.done){n.Ra(4);break}f=e.value;k=c;l=k.set;m=f;return g.A(n,a.u(f),5);case 5:l.call(k,m,n.u);e=d.next();n.Ra(2);break;case 4:return n.return(c)}})},G5=function(a,b,c,d){this.status=a;
this.j=b;this.u=c;this.failureReason=d},H5=function(a,b,c){this.j=a;
this.U=b;this.B=c},NZa=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:c=b.entityKey;f=null==(d=b.actionMetadata)?void 0:null==(e=d.playbackDataActionMetadata)?void 0:e.isEnqueuedForExpiredStreamUrlRefetch;g.ua(n,2);var p;var q=null!=(p=b.actionMetadata)&&p.playbackDataActionMetadata?{maximumDownloadQuality:b.actionMetadata.playbackDataActionMetadata.maximumDownloadQuality}:void 0;return g.A(n,LZa(a,c,{isEnqueuedForExpiredStreamUrlRefetch:f,fS:q}),4);case 4:return(k=n.u)?g.A(n,MZa(a,k,b),5):n.return(I5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));
case 5:return n.return(I5(b,!0,k.orchestrationActions));case 2:return l=g.wa(n),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.Ir&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),k5("PDE handleAdd error"),n.return(I5(b,!1,void 0,m))}})},OZa=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,u,x,y,z;
return g.B(function(D){switch(D.j){case 1:return c=b.entityKey,g.A(D,d5(a.j,{mode:"readonly",vc:!0},function(H){var J=V4(H,c,"playbackData"),L=V4(H,g.JC(g.IC(b.entityKey).entityId,"offlineVideoPolicy"),"offlineVideoPolicy");H=V4(H,g.JC(g.IC(b.entityKey).entityId,"transfer"),"transfer");return g.Rr.all([J,L,H])}),2);
case 2:d=D.u;e=g.r(d);f=e.next().value;k=e.next().value;l=e.next().value;m=f;n=k;p=l;if(!m||!n)return D.return(I5(b,!0));q={lastPlayerResponseTimestampSeconds:m.playerResponseTimestamp,offlineToken:n.offlineToken};t={};if(null==(u=p)?0:u.maximumDownloadQuality)t.maximumDownloadQuality=p.maximumDownloadQuality;g.ua(D,3);return g.A(D,LZa(a,c,{refreshData:q,fS:t}),5);case 5:return(x=D.u)?g.A(D,MZa(a,x,b),6):D.return(I5(b,!1,void 0,"OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED"));case 6:return D.return(I5(b,
!0,x.orchestrationActions));case 3:return y=g.wa(D),z="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",y instanceof g.Ir&&"QUOTA_EXCEEDED"===y.type&&(z="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),D.return(I5(b,!1,void 0,z))}})},LZa=function(a,b,c){var d,e,f;
return g.B(function(k){d=g.eI();var l=a.U,m=c.refreshData,n=c.isEnqueuedForExpiredStreamUrlRefetch,p=c.fS,q={entityKey:b};m&&(q.refreshData=m);n&&(q.isExpiredStreamUrlRefetch=n);p&&(q.downloadParameters=p);e={context:g.qI(l),signatureTimestamp:19135,videos:[q]};f=g.QH(PZa);return k.return(g.aG(d,e,f))})},MZa=function(a,b,c){var d;
return g.B(function(e){if(1==e.j){if(!b.frameworkUpdates||!b.frameworkUpdates.entityBatchUpdate)return e.return();if(!(b.frameworkUpdates.entityBatchUpdate.mutations&&0<b.frameworkUpdates.entityBatchUpdate.mutations.length&&"ENTITY_MUTATION_TYPE_DELETE"===b.frameworkUpdates.entityBatchUpdate.mutations[0].type))return e.Ra(2);d=g.IC(b.frameworkUpdates.entityBatchUpdate.mutations[0].entityKey).entityId;return g.A(e,D5(d,a.j,c,a.B),2)}return g.A(e,eZa(b.frameworkUpdates.entityBatchUpdate),0)})},I5=function(a,
b,c,d){return new G5(b?"OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS":"OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",x5(a),c,d)},J5=function(){F5.apply(this,arguments)},RZa=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=x5(b),g.A(e,g5(a.j,b.entityKey,"transfer"),2);case 2:if(d=e.u)return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(e,3);return g.A(e,QZa(a,b),5);case 5:g.va(e,4);break;case 3:return g.wa(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},SZa=function(a,b){var c,
d;
return g.B(function(e){switch(e.j){case 1:return c=x5(b),g.A(e,g5(a.j,b.entityKey,"transfer"),2);case 2:d=e.u;if(!d||"TRANSFER_STATE_COMPLETE"!==d.transferState)return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(e,3);return g.A(e,QZa(a,b,!0),5);case 5:g.va(e,4);break;case 3:return g.wa(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c))}})},QZa=function(a,b,c){c=void 0===c?!1:c;
var d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return e=null==(d=b.actionMetadata)?void 0:d.transferEntityActionMetadata,l={key:b.entityKey,transferState:"TRANSFER_STATE_TRANSFER_IN_QUEUE",cotn:g.Ku(16),enqueuedTimestampMs:Date.now().toString(),maximumDownloadQuality:null==(f=e)?void 0:f.maximumDownloadQuality,preferredAudioTrack:null==(k=e)?void 0:k.preferredAudioTrack,transferRetryCount:0,isRefresh:c,hasLoggedFirstStarted:!1},m=g.IC(l.key).entityId,g.A(n,d5(a.j,{mode:"readwrite",vc:!0},function(p){var q=
[];c&&q.push($4(p,g.JC(m,"offlineVideoStreams")));q.push(Y4(p,l,"transfer"));return g.Rr.all(q)}),2);
o5({transferStatusType:"TRANSFER_STATUS_TYPE_ENQUEUED",statusType:"ADDED_TO_QUEUE"},{videoId:m,jj:l});g.sa(n)})},TZa=function(a,b,c){return new g.pD(a,{cotn:b,
raw_player_response:c,download_media:!0,start:Infinity,disable_watch_next:!0})},UZa=function(){return{priority:1,
retryScheduleIntervalsInSeconds:[1,2,4]}},K5=function(a,b,c,d,e,f,k,l,m,n,p){this.entityType=a;
this.actionId=b;this.action=c;this.parentActionId=d;this.rootActionId=void 0===e?b:e;this.childActionIds=f;this.prereqActionId=k;this.postreqActionIds=l;this.hasChildActionFailed=n;this.retryScheduleIndex=0;this.j=p||Date.now();this.retryScheduleIndex=m||0},L5=function(a){return{key:g.JC(a.actionId,"offlineOrchestrationActionWrapperEntity"),
actionProto:a.action,parentActionId:a.parentActionId,rootActionId:a.rootActionId,childActionIds:a.childActionIds,prereqActionId:a.prereqActionId,postreqActionIds:a.postreqActionIds,retryScheduleIndex:a.retryScheduleIndex,hasChildActionFailed:a.hasChildActionFailed,enqueueTimeSec:(a.j/1E3).toFixed()}},VZa=function(){this.j=new Map},WZa=function(){M5||(M5=new VZa);
return M5},XZa=function(a,b){return{eventType:{flowEventNamespace:"FLOW_EVENT_NAMESPACE_OFFLINE_ORCHESTRATION",
flowEventType:a},metadata:b,statusCode:void 0,csn:void 0,can:void 0}},YZa=function(a,b,c){if(!c){var d=void 0===d?!1:d;
c=a.j.get("FLOW_TYPE_OFFLINE_ORCHESTRATION");if(!c||d)c=g.Ku(16),a.j.set("FLOW_TYPE_OFFLINE_ORCHESTRATION",c)}a={flowNonce:c,flowType:"FLOW_TYPE_OFFLINE_ORCHESTRATION",flowEventType:b.eventType};b.metadata&&(a.flowMetadata=b.metadata);void 0!==b.statusCode&&(a.flowEventStatus=b.statusCode);b.csn&&(a.csn=b.csn);b.can&&(a.can=b.can);g.yr("flowEvent",a,void 0)},ZZa=function(a,b,c){if(!a.action.entityKey)throw Error("entityKey is missing.");
var d=g.IC(a.action.entityKey);a={entityType:d.nW,entityId:d.entityId,offlineOrchestrationActionType:a.action.actionType,orchestrationAction:{orchestrationActionId:a.actionId}};b&&(a.offlineOrchestrationActionResult=b.status,a.isRetryable=b.j);c&&(a.additionalOrchestrationActions=c.map(function(e){return{orchestrationActionId:e.actionId}}));
return a},N5=function(a,b){var c={offlineOrchestrationContext:ZZa(a)};
b=XZa(b,c);YZa(WZa(),b,a.rootActionId)},O5=function(a,b,c){c=void 0===c?[]:c;
b={offlineOrchestrationContext:ZZa(a,b,c)};b=XZa(3,b);YZa(WZa(),b,a.rootActionId)},$Za=function(){this.actions=[]},a_a=function(a,b){b=g.r(b);
for(var c=b.next();!c.done;c=b.next())c=c.value,N5(c,1),a.actions.push(c);a.actions.sort(a.j)},b_a=function(a,b){a=g.r(a.actions);
for(var c=a.next();!c.done;c=a.next())if(c.value.actionId===b)return!0;return!1},P5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.Y=b;this.V=c;this.D=d;this.j=new $Za;this.N=new g.Qs;this.C=new g.K(function(){e.retry()});
this.I=NaN;g.I(this,this.C);this.J=e5(this.u,this.W.bind(this))},d_a=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return e=new P5(a,b,c,d),g.A(f,c_a(e),2);e.B?Promise.resolve():Q5(e);return f.return(e)})},Q5=function(a){var b,c,d,e,f,k,l,m,n,p,q,t,u,x,y;
return g.B(function(z){switch(z.j){case 1:if(a.B)throw Error("Already processing an action");if(a.isDisposed())return z.return();b=a.j.actions.shift();wZa(a.V,!b);if(void 0===b)return z.return();for(c=[b];;)if((d=a.j.actions[0])&&0===d.retryScheduleIndex&&d.entityType===b.entityType)c.push(a.j.actions.shift());else break;a.B=c;if(e=a.Y[b.entityType]){z.Ra(2);break}a.B=void 0;return g.A(z,Q5(a),3);case 3:return z.return();case 2:f=g.r(c);for(k=f.next();!k.done;k=f.next())l=k.value,N5(l,2);g.ua(z,4,
5);return g.A(z,KZa(e,c.map(function(D){return D.action})),7);
case 7:m=z.u,n=g.r(c),k=n.next();case 8:if(k.done){z.Ra(5);break}p=k.value;q=m.get(p.action);return g.A(z,e_a(a,p,q),9);case 9:k=n.next();z.Ra(8);break;case 5:g.xa(z);a.B=void 0;g.ya(z,6);break;case 4:return t=g.wa(z),k5("Orchestration error",t),g.ua(z,12),g.A(z,f_a(a,c),14);case 14:g.va(z,5);break;case 12:u=g.wa(z);k5("Orchestration retry error",u);x=g.r(c);for(k=x.next();!k.done;k=x.next())y=k.value,3>y.retryScheduleIndex&&a_a(a.j,[y]);z.Ra(5);break;case 6:return g.A(z,Q5(a),0)}})},e_a=function(a,
b,c){var d,e,f,k,l,m;
return g.B(function(n){if(1==n.j){if("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS"===c.status){k=void 0;try{k=null==(l=c.u)?void 0:l.map(function(p){return a.createAction(p,b)})}catch(p){return O5(b,c),m={entityKey:b.action.entityKey,
failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNSUPPORTED_ENTITY_FAILED"},m5(a.D,m),k5("Orchestration subactions creation error",p),n.return()}O5(b,c,k);return g.A(n,d5(a.u,{mode:"readwrite",vc:!0},function(p){var q=[];if(k){var t=k.map(function(u){return L5(u)});
q.push(Z4(p,t,"offlineOrchestrationActionWrapperEntity"))}t=L5(b);q.push($4(p,t.key));return g.Rr.all(q)}),9)}if("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE"!==c.status)return n.Ra(0);
O5(b,c);if(c.j&&3>b.retryScheduleIndex+1)return g.A(n,f_a(a,[b]),0);e=(null==(d=c)?0:d.failureReason)?c.failureReason:"OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN";f={entityKey:b.action.entityKey,failureReason:e};m5(a.D,f);k5("Orchestration result is not retryable, deleting action");return g.A(n,aZa(a.u,L5(b).key),0)}N5(b,4);g.sa(n)})},R5=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,u;
return g.B(function(x){c=[];d=Infinity;e=4E3;f=g.r(b);for(k=f.next();!k.done;k=f.next())l=k.value,m=Number(l.enqueueTimeSec),n=g_a(m),p=l.retryScheduleIndex,q=null!=p&&0<p,0<n&&q?(d=Math.min(d,m),e=Math.min(n,e)):c.push(l);isFinite(d)&&(!a.C.isActive()||d<a.I)&&(a.I=d,a.C.start(e));a.N.vf()||(t=c.length,c=c.filter(function(y){var z;y=(null==(z=y.actionProto)?void 0:z.actionType)||"OFFLINE_ORCHESTRATION_ACTION_TYPE_UNKNOWN";return!h_a.includes(y)}),u=c.length<t,!a.C.isActive()&&u&&a.C.start(1));
0<c.length&&i_a(a,c);return g.A(x,a.B?Promise.resolve():Q5(a),0)})},k_a=function(a){var b,c,d,e,f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,j_a(a),2);b=m.u;c=[];d=g.r(b);for(e=d.next();!e.done;e=d.next())f=e.value,k=g.IC(f.key),l=k.entityId,b_a(a.j,l)||c.push(f);return g.A(m,R5(a,c),0)})},g_a=function(a){a=1E3*a-Date.now();
return 4E3<a?4E3:a},f_a=function(a,b){var c,d,e;
return g.B(function(f){c=g.r(b);for(d=c.next();!d.done;d=c.next()){e=d.value;var k=void 0,l=void 0,m=(null==(l=e.action)?void 0:null==(k=l.actionMetadata)?void 0:k.retryScheduleIntervalsInSeconds)||[1,2,4];k=1;e.retryScheduleIndex<m.length&&(k=m[e.retryScheduleIndex]);e.j=1E3*k+Date.now();e.retryScheduleIndex++}return g.A(f,l_a(a,b),0)})},c_a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,h5(a.u,"offlineOrchestrationActionWrapperEntity"),2);b=c.u;return g.A(c,R5(a,b),0)})},i_a=function(a,b){0!==b.length&&b.forEach(function(c){if(!c.key)throw Error("Entity key is required.");
if(!c.actionProto)throw Error("OfflineOrchestrationAction is required.");var d=g.IC(c.key),e=g.IC(c.actionProto.entityKey);c=new K5(e.entityType,d.entityId,c.actionProto,c.parentActionId,c.rootActionId,c.childActionIds,c.prereqActionId,c.postreqActionIds,c.retryScheduleIndex,c.hasChildActionFailed,1E3*Number(c.enqueueTimeSec));3>c.retryScheduleIndex&&a_a(a.j,[c])})},j_a=function(a,b){var c;
return g.B(function(d){if(1==d.j)return g.A(d,h5(a.u,"offlineOrchestrationActionWrapperEntity",b),2);c=d.u;return d.return(c.filter(fZa))})},l_a=function(a,b){if(0===b.length)return Promise.resolve([]);
b=b.map(function(c){return L5(c)});
return $Ya(a.u,b)},m_a=function(){this.j=void 0},o_a=function(a,b){var c,d,e,f,k;
return g.B(function(l){c=b.videoId;d=b.S();e=!0;if(b.captionTracks.length)f=FYa(b),a.j=new g.bJ(d,b,f);else if(b.Kc)k=g.Oxa(b),a.j=new g.dJ(d,b.Kc,c,k,b.Al),e=b.Al;else return l.return();return l.return(new Promise(function(m){var n;null==(n=a.j)||n.bv(function(){return g.B(function(p){if(1==p.j)return g.A(p,n_a(a,c,e),2);m();g.sa(p)})})}))})},n_a=function(a,b,c){c=void 0===c?!0:c;
var d,e,f,k,l,m,n,p,q,t,u,x,y,z;return g.B(function(D){switch(D.j){case 1:if(!a.j)return D.return();d=[];e=g.ZI(a.j.u,c);f=[];k={};l=g.r(e.entries());for(m=l.next();!m.done;k={UD:k.UD},m=l.next())n=m.value,p=g.r(n),q=p.next().value,t=p.next().value,k.UD=q,u=t,x=a.j.Hr(u,"json3"),y=g.vq(x,{withCredentials:!0,format:"RAW"},3,500).then(function(H){return function(J){J={metadata:g.aD(e[H.UD]),trackData:J.xhr.responseText};f.push(J)}}(k)).Ii(function(H){k5("Caption fetch error",H)}),d.push(y);
return g.A(D,GYa(d),2);case 2:return g.ua(D,3),g.A(D,jZa(b,f),5);case 5:g.va(D,0);break;case 3:z=g.wa(D),k5("Caption DB transaction error",z),g.sa(D)}})},p_a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,kZa(a),2);b=c.u;return c.return(!!b&&0<b.length)})},q_a=function(a,b){this.api=a;
this.j=b;this.logger=new g.uO("woffle");this.u=!1},r_a=function(a){return g.B(function(b){return b.return(lZa(a))})},s_a=function(a){var b;
return g.B(function(c){if(1==c.j)return g.A(c,g.zwa(a),2);b=c.u;return c.return(b.filter(function(d){return!!d.url}).map(function(d){return d.url}))})},S5=function(a,b){var c=g.UC(b);
if(1===c||0===c)return Promise.resolve();(c=t_a(a,b))&&c.stopVideo();a.B=0;return r_a(b)},T5=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?!0:d;var e="string"===typeof b?b:b.videoDetails.videoId;2===g.UC(e)&&((b=t_a(a,e))?b.stopVideo():a.logger.info(function(){return"Corresponding player for "+e+" not found. Pausing anyway"}),g.VC(e,2),a.B=2,c?u_a(a.j):d&&v_a(a.j))},t_a=function(a,b){var c;
return(null==(c=a.player)?void 0:c.getVideoData().videoId)===b?a.player:null},w_a=function(a){switch(a){case "HD_1080":return"hd1080";
case "HD":return"hd720";case "SD":return"large";case "LD":return"tiny";default:return"hd720"}},U5=function(a){g.G.call(this);
this.j=a;this.u=e5(this.j,this.B.bind(this))},x_a=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:if(0===b.length)return n.return([]);c=b.map(function(p){return g.JC(p,"transfer")});
return g.A(n,h5(a.j,"transfer",c),2);case 2:d=n.u;e=d.filter(fZa).map(function(p){return g.IC(p.key).entityId});
f=b.filter(function(p){return-1===e.indexOf(p)});
if(0===f.length)return n.return([]);k=g.r(f);l=k.next();case 3:if(l.done){n.Ra(5);break}m=l.value;return g.A(n,r_a(m),4);case 4:l=k.next();n.Ra(3);break;case 5:return n.return(f)}})},z_a=function(a,b,c,d,e,f){var k,l,m;
return g.B(function(n){k="STREAM_TYPE_UNKNOWN";c.video&&c.audio?(k="STREAM_TYPE_AUDIO_AND_VIDEO",k5("unexpected stream type")):c.video&&!c.audio?k="STREAM_TYPE_VIDEO":!c.video&&c.audio&&(k="STREAM_TYPE_AUDIO");l=g.JC(b,"offlineVideoStreams");m={numBytesDownloaded:e.toFixed(),numTotalBytes:f.toFixed(),streamType:k,streamState:"DOWNLOAD_STREAM_STATE_IN_PROGRESS",formatStreamBytes:JSON.stringify(d),itag:"STREAM_TYPE_AUDIO_AND_VIDEO"===k?Number(c.Wb()):void 0};return g.A(n,d5(a,{mode:"readwrite",vc:!0},
function(p){var q=V4(p,l,"offlineVideoStreams"),t=V4(p,g.JC(b,"transfer"),"transfer");return g.Rr.all([q,t]).then(function(u){var x=g.r(u);u=x.next().value;x=x.next().value;if(!x)return $4(p,l).then(function(){});
u=[Y4(p,y_a(u,d,m,l),"offlineVideoStreams")];x.offlineVideoStreams||(x.offlineVideoStreams=[]);-1===x.offlineVideoStreams.indexOf(l)&&(x.offlineVideoStreams.push(l),u.push(Y4(p,x,"transfer")));return g.Rr.all(u)})}),0)})},A_a=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.JC(b,"offlineVideoStreams"),g.A(l,g5(a,c,"offlineVideoStreams"),2);d=l.u;if(!d||!d.streamsProgress)return l.return();e=g.r(d.streamsProgress);for(f=e.next();!f.done;f=e.next())k=f.value,k.streamState="DOWNLOAD_STREAM_STATE_COMPLETE",k.numTotalBytes!==k.numBytesDownloaded&&(k.numBytesDownloaded=k.numTotalBytes);return g.A(l,f5(a,d,"offlineVideoStreams"),0)})},y_a=function(a,b,c,d){if(a&&a.streamsProgress){d=a;
a:{b=b.itag+";"+b.xtags;for(var e=a.streamsProgress,f=0;f<e.length;f++){var k=JSON.parse(e[f].formatStreamBytes);if(k.itag+";"+k.xtags===b){e[f]=c;c=e;break a}}e.push(c);c=e}d.streamsProgress=c}else a={key:d,streamsProgress:[c]};return a},V5=function(a,b,c,d){g.G.call(this);
var e=this;this.u=a;this.api=b;this.va=c;this.oa=d;this.D=new g.Qs;this.C=new g.K(function(){e.j&&"TRANSFER_STATE_TRANSFERRING"===e.j.transferState&&e.D.vf()&&(3>(e.j.transferRetryCount||0)?T5(e.I,e.B,!1,!1):S5(e.I,e.B.videoDetails.videoId),e.xs("TRANSFER_FAILURE_REASON_TIMEOUT_NO_PROGRESS"))});
this.V=0;this.ma=new g.mz(this);this.J=e5(this.u,this.SS.bind(this));this.I=new q_a(b,this);this.Fa=new m_a;this.N=new U5(this.u);this.Y=this.D.La("publicytnetworkstatus-online",this.Az.bind(this));this.W=this.D.La("publicytnetworkstatus-offline",this.k0.bind(this));g.I(this,this.ma);this.ma.P(b,"offlinetransferpause",this.l0);this.Da=g.hA(this.api.S().experiments,"web_player_transfer_timeout_threshold_ms")},B_a=function(a){return g.B(function(b){if(1==b.j)b=g.A(b,iZa(),2);
else{var c=a.N;var d=g.TC();d=Object.keys(d);c=x_a(c,d);b=g.A(b,c,0)}return b})},X5=function(a,b){b=void 0===b?!1:b;
var c;return g.B(function(d){if(1==d.j){if(a.j)throw Error("Already downloading a video");return g.A(d,C_a(a),2)}return 4!=d.j?(c=d.u,xZa(a.va,!c),c&&a.D.vf()?b?g.A(d,new Promise(function(e){g.nq(e,1E3)}),4):d.Ra(4):(!c&&a.j&&W5(a),d.Ra(0))):g.A(d,D_a(a,c),0)})},E_a=function(a){return g.B(function(b){if(1==b.j)return a.B?g.A(b,S5(a.I,a.B.videoDetails.videoId),3):b.Ra(0);
W5(a);g.sa(b)})},F_a=function(a,b){var c,d,e;
return g.B(function(f){switch(f.j){case 1:return g.ua(f,2),(c=!!b.captionTracks.length||!!b.Kc)?g.A(f,p_a(b.videoId),4):f.return();case 4:return(d=f.u)?f.return():g.A(f,o_a(a.Fa,b),5);case 5:g.va(f,0);break;case 2:e=g.wa(f),k5("Caption downloading error",e,b.cotn),g.sa(f)}})},D_a=function(a,b){var c,d,e,f,k;
return g.B(function(l){switch(l.j){case 1:return a.j=b,c=g.IC(a.j.key),"TRANSFER_STATE_TRANSFERRING"===a.j.transferState&&o5({transferStatusType:"TRANSFER_STATUS_TYPE_RESUME_PROCESSING",statusType:"OFFLINING_RETRIED"},{videoId:c.entityId,jj:a.j}),g.A(l,Y5(a),2);case 2:return d=null,g.ua(l,3),g.A(l,G_a(a,b),5);case 5:d=l.u;a.B=d;g.va(l,4);break;case 3:return e=g.wa(l),k5("error getting player response",e,b.cotn),g.A(l,a.xs("TRANSFER_FAILURE_REASON_INTERNAL"),6);case 6:return l.return();case 4:return f=
TZa(a.api.S(),b.cotn,d),g.A(l,F_a(a,f),7);case 7:return k=f,g.A(l,s_a(f.videoId),8);case 8:k.Ym=l.u;var m=a.I,n=b.maximumDownloadQuality;f.getPlayerResponse();g.VC(f.videoId,2);m.B=2;m.u=!1;var p;null==(p=m.player)||p.dispose();m.player=m.api.Yo(9,f);p={};g.mu(m.player,(p.localmediachange=m.GC,p.signatureexpired=m.mI,p.statechange=m.aZ,p),m);n=w_a(n);m.K("hoffle_lmqf_killswitch")||g.RMa(m.player,g.Ow(n,n,!0,"m"),!1);g.JN(m.player,!1);Z5(a);g.sa(l)}})},C_a=function(a){var b,c;
return g.B(function(d){if(1==d.j)return g.A(d,h5(a.u,"transfer"),2);b=d.u;c=b.filter(H_a).sort(I_a);return 0===c.length?d.return():d.return(c[0])})},Y5=function(a){return g.B(function(b){Z5(a);
return g.A(b,$5(a,"TRANSFER_STATE_TRANSFERRING"),0)})},u_a=function(a){var b;
g.B(function(c){if(1==c.j)return a.C.stop(),g.A(c,$5(a,"TRANSFER_STATE_PAUSED_BY_USER"),2);b=g.IC(a.j.key);zZa({videoId:b.entityId,jj:a.j});W5(a);X5(a);g.sa(c)})},v_a=function(a){g.B(function(b){if(1==b.j)return a.C.stop(),g.A(b,$5(a,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),2);
W5(a);g.sa(b)})},J_a=function(a){var b,c,d;
g.B(function(e){switch(e.j){case 1:a.C.stop();if(!a.j||!a.B){e.Ra(2);break}b=TZa(a.api.S(),a.j.cotn,a.B);return g.A(e,F_a(a,b),2);case 2:return g.A(e,$5(a,"TRANSFER_STATE_COMPLETE","DOWNLOAD_STREAM_STATE_COMPLETE"),4);case 4:return c=g.IC(a.j.key),d=c.entityId,g.A(e,A_a(a.u,d),5);case 5:o5({transferStatusType:"TRANSFER_STATUS_TYPE_COMPLETED",statusType:"SUCCESS"},{videoId:d,jj:a.j}),W5(a),X5(a),g.sa(e)}})},L_a=function(a,b,c){var d;
g.B(function(e){switch(e.j){case 1:if("TRANSFER_STATE_TRANSFERRING"===a.j.transferState){e.Ra(2);break}return g.A(e,Y5(a),2);case 2:d=Date.now();if(!(1E3<d-a.V)){e.Ra(4);break}a.V=d;return g.A(e,z_a(a.u,c.videoId,c.u,c.formatStream,c.bytesDownloaded,c.j),5);case 5:if(a.j.hasLoggedFirstStarted){yZa({videoId:b,jj:a.j},c.bytesDownloaded,c.j);e.Ra(4);break}a.j.hasLoggedFirstStarted=!0;return g.A(e,K_a(a),7);case 7:yZa({videoId:b,jj:a.j},c.bytesDownloaded,c.j,!0);case 4:Z5(a),g.sa(e)}})},M_a=function(a){var b=
3>(a.j.transferRetryCount||0);
b&&(a=a.j,a.transferRetryCount=(a.transferRetryCount||0)+1);return b},N_a=function(a,b){b=void 0===b?"TRANSFER_FAILURE_REASON_UNKNOWN":b;
var c,d;return g.B(function(e){if(1==e.j)return c="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN","TRANSFER_FAILURE_REASON_NETWORK"===b?c="OFFLINE_OPERATION_FAILURE_REASON_NETWORK_REQUEST_FAILED":"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"===b&&(c="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),g.A(e,$5(a,"TRANSFER_STATE_FAILED","DOWNLOAD_STREAM_STATE_ERROR_STREAMS_MISSING",b),2);m5(a.oa,{entityKey:a.j.key,failureReason:c});d=g.IC(a.j.key).entityId;var f={videoId:d,jj:a.j},k=b,l={transferStatusType:"TRANSFER_STATUS_TYPE_TERMINATED_WITH_FAILURE",
statusType:"FAILED"};k&&(l.transferFailureReason=k,l.failureReason=AZa(k));o5(l,f);g.sa(e)})},$5=function(a,b,c,d){var e;
return g.B(function(f){if(1==f.j)return a.j.transferState=b,a.j.failureReason=d,g.ua(f,2),g.A(f,K_a(a,function(k){return c?W4(k,"offlineVideoStreams",a.j.offlineVideoStreams).then(function(l){for(var m=g.r(l),n=m.next();!n.done;n=m.next())if((n=n.value)&&n.streamsProgress){n=g.r(n.streamsProgress);for(var p=n.next();!p.done;p=n.next())p.value.streamState=c}return Z4(k,l.filter(function(q){return!!q}),"offlineVideoStreams")}):g.Rr.resolve(void 0)}),4);
if(2!=f.j)return g.va(f,0);e=g.wa(f);return e instanceof g.Ir&&"QUOTA_EXCEEDED"===e.type?g.A(f,a.xs("TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE"),0):f.Ra(0)})},K_a=function(a,b){var c;
return g.B(function(d){if(!a.j)return d.return();c=a.j;return g.A(d,d5(a.u,{mode:"readwrite",vc:!0},function(e){var f=[Y4(e,c,"transfer")];b&&f.push(b(e));return g.Rr.all(f)}),0)})},W5=function(a){a.j=void 0;
a.B=void 0;a.C.stop()},G_a=function(a,b){var c,d,e,f,k;
return g.B(function(l){if(1==l.j)return c=g.IC(b.key),d=c.entityId,e=g.JC(d,"playbackData"),g.A(l,g5(a.u,e,"playbackData"),2);f=l.u;if(null==(k=f)?0:k.playerResponseJson)return l.return(JSON.parse(f.playerResponseJson));throw Error("No PlayerResponse found");})},Z5=function(a){a.C.start(a.Da||18E5)},H_a=function(a){return void 0!==a6[a.transferState]},I_a=function(a,b){var c=a6[a.transferState],d=a6[b.transferState];
return c!==d?c-d:Number(a.enqueuedTimestampMs)-Number(b.enqueuedTimestampMs)},b6=function(a,b){var c=this;
this.U=a;this.api=b;this.N=new g.Qs;this.B=new tZa(function(){return O_a(c)},function(){P_a(c)},this.api.Cp(),this.api.K.bind(this.api));
this.u=new l5(this.api);this.C=new g.ti;uZa(this.B)},O_a=function(a){return g.B(function(b){a.api.Ma("onOrchestrationBecameLeader");
a.j&&a.D||Q_a(a).then(a.C.resolve).catch(a.C.reject);var c=a.C.promise;return g.A(b,c,0)})},Q_a=function(a){var b,c,d;
return g.B(function(e){if(1==e.j)return g.A(e,j5(),2);if(3!=e.j){b=e.u;if(!b)return k5("PES is undefined"),e.return();a.j=new V5(b,a.api,a.B,a.u);c=a.Sx(b);d=a;return g.A(e,d_a(b,c,a.B,a.u),3)}d.D=e.u;return g.A(e,R_a(a),0)})},R_a=function(a){var b;
return g.B(function(c){switch(c.j){case 1:if(!a.j)return k5("transferManager is undefined"),c.return();if(a.j.j){c.Ra(2);break}return g.A(c,X5(a.j),2);case 2:return g.A(c,a.wz(),4);case 4:return a.J=g.oq(function(){a.wz()},9E5),g.or(g.qr(),function(){return a.eJ()}),g.A(c,j5(),5);
case 5:return b=c.u,g.A(c,pZa(b),6);case 6:vZa(a.B),g.sa(c)}})},P_a=function(a){var b,c;
g.B(function(d){if(1==d.j)return a.j||a.D?g.A(d,a.C.promise,2):d.return();void 0!==a.J&&(window.clearInterval(a.J),a.J=void 0);null==(b=a.j)||b.dispose();a.j=void 0;null==(c=a.D)||c.dispose();a.D=void 0;a.api.Ma("onOrchestrationLostLeader");a.C=new g.ti;g.sa(d)})},S_a=function(){var a,b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return g.A(k,j5(),2);case 2:a=k.u;if(!a)return k.return([]);b=Date.now()/1E3;return g.A(k,h5(a,"offlineVideoPolicy"),3);case 3:c=k.u,d=g.r(c),e=d.next();case 4:if(e.done){k.Ra(6);break}f=e.value;if(!(f.expirationTimestamp&&Number(f.expirationTimestamp)<b)){k.Ra(5);break}f.action="OFFLINE_VIDEO_POLICY_ACTION_DISABLE";return g.A(k,f5(a,f,"offlineVideoPolicy"),5);case 5:e=d.next();k.Ra(4);break;case 6:return k.return(c.map(function(l){return l.key}))}})},c6=
function(a,b,c,d,e){var f,k,l;
return g.B(function(m){if(1==m.j)return g.A(m,j5(),2);f=m.u;if(!f)return m.return([]);k=b.map(function(n){var p=g.JC(n,c);p={actionType:d,entityKey:p,actionMetadata:Object.assign({},UZa(),e)};"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"!==d&&(p.actionMetadata.priority=0);n=new K5(c,n,p);return L5(n)});
l=$Ya(f,k);uZa(a.B);return m.return(l)})},d6=function(a){var b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return b=g.eI(),c=mZa(a),d=g.QH(T_a),g.ua(k,2),g.A(k,g.aG(b,c,d),4);case 4:e=k.u;g.va(k,3);break;case 2:throw f=g.wa(k),k5("GetOffline fetch request error",f),Error("GetOffline fetch request error");case 3:if(!e)throw Error("Network request failed");if(!e.videos||!e.videos.length)throw Error("No data");return k.return(e.videos.map(function(l){return l.offlineVideoData}))}})},U_a=function(a){var b,c,d,e,f;
return g.B(function(k){switch(k.j){case 1:return b=g.eI(),c=nZa(a),d=g.QH(T_a),g.ua(k,2),g.A(k,g.aG(b,c,d),4);case 4:e=k.u;g.va(k,3);break;case 2:throw f=g.wa(k),k5("GetOffline fetch request error for playlist",f),Error("GetOffline fetch request error for playlist");case 3:if(!e)throw Error("Network request failed");if(!e.playlists||!e.playlists.length)throw Error("No data");return k.return(e.playlists.map(function(l){return l.offlinePlaylistData}))}})},e6=function(a,b,c){this.j=a;
this.U=b;this.B=c},X_a=function(a,b){var c,d,e,f,k,l,m,n,p,q,t,u,x;
return g.B(function(y){switch(y.j){case 1:return c=x5(b),d=g.IC(b.entityKey),e=d.entityId,f=[],g.ua(y,2),g.A(y,V_a(a,e),4);case 4:f=y.u;g.va(y,3);break;case 2:return k=g.wa(y),l="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",k instanceof g.Ir&&"QUOTA_EXCEEDED"===k.type&&(l="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),y.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,l));case 3:m=[];if(null==(n=f)?0:n.length)for(p=g.r(f),q=p.next();!q.done;q=p.next())if(t=q.value,u=
t.offlineVideoData,x=void 0,null==(x=u)?0:x.videoId){var z=m,D=z.push,H=void 0,J={offlineVideoData:u};if(null==(H=b.actionMetadata)?0:H.mainPlaylistEntityActionMetadata)J.maximumDownloadQuality=b.actionMetadata.mainPlaylistEntityActionMetadata.maximumDownloadQuality;J={mainVideoEntityActionMetadata:J};H=g.JC(u.videoId,"mainVideoEntity");J=Object.assign({},J,{priority:0,retryScheduleIntervalsInSeconds:W_a});D.call(z,{actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",entityKey:H,actionMetadata:J})}return y.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",
c,m))}})},Y_a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=x5(b),g.ua(e,2),d=g.IC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,E5(a.j,b,a.B),5):g.A(e,IZa(d,a.j,b,a.B),5);case 5:g.va(e,3);break;case 2:return g.wa(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},V_a=function(a,b){var c,d,e,f,k,l;
return g.B(function(m){switch(m.j){case 1:return g.A(m,U_a([b]),2);case 2:return c=m.u,g.A(m,Z_a(a,c[0]),3);case 3:return d=m.u,e=d.mainPlaylistEntity,f=d.q0,g.ua(m,4),k=GZa(e,f.avatar),g.A(m,w5(k),6);case 6:g.va(m,5);break;case 4:if(l=g.wa(m),!a.U.K("woffle_disable_thumbnails"))throw l;case 5:return m.return(c[0].videos)}})},Z_a=function(a,b){var c=void 0,d,e,f,k,l,m,n,p,q,t,u,x,y;
return g.B(function(z){if(1==z.j){if(!(b&&b.playlistId&&b.channel&&b.channel.offlineChannelData))throw Error("Invalid OfflinePlaylistData");c||(c=Date.now().toString());d=b.videos;e=[];f=[];if(d)for(k=g.r(d),l=k.next();!l.done;l=k.next()){m=l.value;n=m.offlineVideoData;if(!n||!n.videoId)throw Error("Invalid offlineVideoData");p=n.videoId;q={id:g.JC(p,"mainPlaylistVideoEntity"),video:g.JC(p,"mainVideoEntity")};e.push(q);f.push(q.id)}t=b.playlistId;u=b.channel.offlineChannelData;x=$_a(g.JC(t,"ytMainChannelEntity"),
u);y={key:g.JC(t,"mainPlaylistEntity"),playlistId:t,channelOwner:x.id,videos:f,title:b.title,thumbnailStyleData:a0a(b),visibility:b0a(b)};return g.A(z,d5(a.j,{mode:"readwrite",vc:!0},function(D){for(var H=Y4(D,y,"mainPlaylistEntity"),J=Y4(D,x,"ytMainChannelEntity"),L=[],ba=g.r(e),M=ba.next();!M.done;M=ba.next())L.push(Y4(D,M.value,"mainPlaylistVideoEntity"));return g.Rr.all([H,J].concat(g.v(L)))}),2)}return z.return({mainPlaylistEntity:y,
q0:x,xka:e})})},$_a=function(a,b){if(!(b.channelId&&b.title&&b.thumbnail))throw Error("Invalid OfflineChannelData");
return{id:a,channelId:b.channelId,title:b.title,avatar:b.thumbnail}},a0a=function(a){var b=[],c=a.videos;
c&&0<c.length&&b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_FIRST_VIDEO"),value:{collageThumbnail:{coverThumbnail:c[0].offlineVideoData.thumbnail}}});if((a=a.additionalMetadadatas)&&0<a.length)for(a=g.r(a),c=a.next();!c.done;c=a.next()){var d=c.value.offlineBundleItemPlaylistData,e=void 0;c=null==(e=d)?void 0:e.style;e=void 0;d={collageThumbnail:{coverThumbnail:null==(e=d)?void 0:e.coverThumbnail}};switch(c){case "BUNDLE_ITEM_STYLE_UNSPECIFIED":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_UNKNOWN"),
value:d});break;case "BUNDLE_ITEM_STYLE_TWO_BY_TWO":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_TWO_BY_TWO"),value:d});break;case "BUNDLE_ITEM_STYLE_ONE_AND_TWO_AVATAR":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_ONE_AND_TWO_AVATAR"),value:d});break;case "BUNDLE_ITEM_STYLE_ONE_AND_TWO":b.push({key:Number("PLAYLIST_THUMBNAIL_STYLE_ONE_AND_TWO"),value:d})}}return b},b0a=function(a){switch(a.privacy){case "PRIVATE":return"PLAYLIST_VISIBILITY_PRIVATE";
case "PUBLIC":return"PLAYLIST_VISIBILITY_PUBLIC";case "UNLISTED":return"PLAYLIST_VISIBILITY_UNLISTED";default:return"PLAYLIST_VISIBILITY_UNKNOWN"}},f6=function(a,b,c){this.j=a;
this.U=b;this.B=c},e0a=function(a,b){var c,d,e,f,k,l,m,n;
return g.B(function(p){switch(p.j){case 1:return c=x5(b),d=g.IC(b.entityKey),e=d.entityId,g.ua(p,2),g.A(p,c0a(a,e,void 0,null==(f=b.actionMetadata)?void 0:null==(k=f.mainVideoEntityActionMetadata)?void 0:k.offlineVideoData),4);case 4:g.va(p,3);break;case 2:return l=g.wa(p),m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",l instanceof g.Ir&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),p.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m));
case 3:var q;var t=null!=(q=b.actionMetadata)&&q.mainVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.mainVideoEntityActionMetadata.maximumDownloadQuality}}:void 0;n=d0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,t);return p.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[n]))}})},f0a=function(a,b){var c,d,e,f,k,l,m,n,p;
return g.B(function(q){switch(q.j){case 1:return c=x5(b),d=g.IC(b.entityKey),e=d.entityId,g.A(q,g5(a.j,b.entityKey,"mainVideoEntity"),2);case 2:f=q.u;if(!f){k=void 0;q.Ra(3);break}return g.A(q,g5(a.j,f.downloadState,"mainVideoDownloadStateEntity"),4);case 4:k=q.u;case 3:l=k;if(!f||!l)return q.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(q,5);return g.A(q,c0a(a,e,l.addedTimestampMillis),7);case 7:m=d0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.va(q,6);break;case 5:return n=
g.wa(q),n instanceof Error&&"No data"===n.message?g.A(q,D5(e,a.j,b,a.B),6):(p="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",n instanceof g.Ir&&"QUOTA_EXCEEDED"===n.type&&(p="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),q.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,p)));case 6:return q.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,m?[m]:void 0))}})},g0a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=x5(b),g.ua(e,2),d=g.IC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,E5(a.j,b,a.B),5):g.A(e,D5(d,a.j,b,a.B),5);case 5:g.va(e,3);break;case 2:return g.wa(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},c0a=function(a,b,c,d){var e,f,k,l,m,n;
return g.B(function(p){switch(p.j){case 1:if(e=d){p.Ra(2);break}return g.A(p,d6([b]),3);case 3:f=p.u,e=f[0];case 2:return g.A(p,h0a(a,e,c),4);case 4:k=p.u;l=k.mainVideoEntity;m=k.channelEntity;g.ua(p,5);var q=B5(l.thumbnail),t=B5(m.avatar);return g.A(p,w5(q.concat(t)),7);case 7:g.va(p,0);break;case 5:n=g.wa(p);if(!a.U.K("woffle_disable_thumbnails"))throw n;g.sa(p)}})},h0a=function(a,b,c){var d,e,f,k,l;
return g.B(function(m){if(1==m.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.JC(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};k={key:g.JC(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.JC(b.videoId,"playbackData"),addedTimestampMillis:c};l={key:g.JC(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,
thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:k.key};return g.A(m,d5(a.j,{mode:"readwrite",vc:!0},function(n){var p=Y4(n,f,"ytMainChannelEntity"),q=Y4(n,k,"mainVideoDownloadStateEntity");n=Y4(n,l,"mainVideoEntity");return g.Rr.all([p,q,n])}),2)}return m.return({mainVideoEntity:l,
channelEntity:f})})},d0a=function(a,b,c){b=g.JC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:i0a});return{actionType:a,entityKey:b,actionMetadata:c}},g6=function(a,b,c){this.j=a;
this.U=b;this.B=c},l0a=function(a,b){var c,d,e,f,k,l;
return g.B(function(m){switch(m.j){case 1:return c=x5(b),d=g.IC(b.entityKey),e=d.entityId,g.ua(m,2),g.A(m,j0a(a,e),4);case 4:g.va(m,3);break;case 2:return f=g.wa(m),k="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.Ir&&"QUOTA_EXCEEDED"===f.type&&(k="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,k));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.ytMainDownloadedVideoEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.ytMainDownloadedVideoEntityActionMetadata.maximumDownloadQuality}}:
void 0;l=k0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",e,p);return m.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},m0a=function(a,b){var c,d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return c=x5(b),d=g.IC(b.entityKey),e=d.entityId,g.A(n,g5(a.j,b.entityKey,"ytMainDownloadedVideoEntity"),2);case 2:f=n.u;if(!f)return n.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(n,3);return g.A(n,j0a(a,e,f.addedTimestampMillis),5);case 5:k=k0a("OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH",e);g.va(n,4);break;case 3:return l=g.wa(n),l instanceof Error&&"No data"===l.message?g.A(n,D5(e,a.j,b,a.B),4):(m="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",
l instanceof g.Ir&&"QUOTA_EXCEEDED"===l.type&&(m="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),n.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,m)));case 4:return n.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,k?[k]:void 0))}})},n0a=function(a,b){var c,d;
return g.B(function(e){switch(e.j){case 1:return c=x5(b),g.ua(e,2),d=g.IC(b.entityKey).entityId,"!*$_ALL_ENTITIES_!*$"===d?g.A(e,E5(a.j,b,a.B),5):g.A(e,D5(d,a.j,b,a.B),5);case 5:g.va(e,3);break;case 2:return g.wa(e),e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 3:return e.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})},j0a=function(a,b,c){var d,e,f,k,l,m;
return g.B(function(n){switch(n.j){case 1:return g.A(n,d6([b]),2);case 2:return d=n.u,e=d[0],g.A(n,o0a(a,e,c),3);case 3:f=n.u;k=f.videoEntity;l=f.channelEntity;g.ua(n,4);var p=B5(k.thumbnail),q=B5(l.avatar);return g.A(n,w5(p.concat(q)),6);case 6:g.va(n,0);break;case 4:m=g.wa(n);if(!a.U.K("woffle_disable_thumbnails"))throw m;g.sa(n)}})},o0a=function(a,b,c){var d,e,f,k,l,m,n;
return g.B(function(p){if(1==p.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=null==(d=b.channel)?void 0:d.offlineChannelData;f={id:g.JC(b.videoId,"ytMainChannelEntity"),channelId:e.channelId,title:e.title,avatar:e.thumbnail};k={id:g.JC(b.videoId,"ytMainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):
void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,channelOwner:f.id};l={id:g.JC(b.videoId,"ytMainDownloadedVideoEntity"),video:k.id,playbackData:g.JC(b.videoId,"playbackData"),offlineVideoPolicy:g.JC(b.videoId,"offlineVideoPolicy"),addedTimestampMillis:c};return a.U.K("woffle_entity_migration")?(m={key:g.JC(b.videoId,"mainVideoDownloadStateEntity"),playbackData:g.JC(b.videoId,"playbackData"),addedTimestampMillis:c},
n={key:g.JC(b.videoId,"mainVideoEntity"),videoId:b.videoId,title:b.title,thumbnail:b.thumbnail,localizedStrings:{viewCount:b.shortViewCountText},lengthSeconds:b.lengthSeconds?Number(b.lengthSeconds):void 0,publishedTimestampMillis:b.publishedTimestamp?(1E3*Number(b.publishedTimestamp)).toString():void 0,formattedDescription:b.description,owner:f.id,downloadState:m.key},g.A(p,d5(a.j,{mode:"readwrite",vc:!0},function(q){var t=Y4(q,f,"ytMainChannelEntity"),u=Y4(q,k,"ytMainVideoEntity"),x=Y4(q,l,"ytMainDownloadedVideoEntity"),
y=Y4(q,m,"mainVideoDownloadStateEntity");q=Y4(q,n,"mainVideoEntity");return g.Rr.all([t,u,x,y,q])}),3)):g.A(p,d5(a.j,{mode:"readwrite",
vc:!0},function(q){var t=Y4(q,f,"ytMainChannelEntity"),u=Y4(q,k,"ytMainVideoEntity");q=Y4(q,l,"ytMainDownloadedVideoEntity");return g.Rr.all([t,u,q])}),3)}return p.return({videoEntity:k,
channelEntity:f,Lja:l})})},k0a=function(a,b,c){b=g.JC(b,"playbackData");
c=Object.assign({},c,{priority:1,retryScheduleIntervalsInSeconds:p0a});return{actionType:a,entityKey:b,actionMetadata:c}},h6=function(){b6.apply(this,arguments);
this.I="ytMainDownloadedVideoEntity"},q0a=function(){var a;
return g.B(function(b){return 1==b.j?g.A(b,j5(),2):(a=b.u)?g.A(b,d5(a,{mode:"readwrite",vc:!0},function(c){var d=W4(c,"ytMainDownloadedVideoEntity"),e=W4(c,"ytMainVideoEntity"),f=W4(c,"mainVideoEntity");return g.Rr.all([d,e,f]).then(function(k){k=g.r(k);var l=k.next().value,m=k.next().value,n=k.next().value;k={};l=g.r(l);for(var p=l.next();!p.done;p=l.next()){p=p.value;var q=g.IC(p.id).entityId;k[q]=p}l={};m=g.r(m);for(p=m.next();!p.done;p=m.next())p=p.value,q=g.IC(p.id).entityId,l[q]=p;m={};n=g.r(n);
for(p=n.next();!p.done;p=n.next())p=p.value,q=g.IC(p.key).entityId,m[q]=p;n=[];p=g.r(Object.keys(k));for(q=p.next();!q.done;q=p.next())if(q=q.value,!m[q]&&l[q]){var t=k[q],u=l[q];t={key:g.JC(q,"mainVideoDownloadStateEntity"),playbackData:g.JC(q,"playbackData"),addedTimestampMillis:t.addedTimestampMillis};q=[{key:g.JC(q,"mainVideoEntity"),videoId:q,title:u.title,thumbnail:u.thumbnail,localizedStrings:u.localizedStrings,lengthSeconds:u.lengthSeconds,publishedTimestampMillis:u.publishedTimestampMillis,
formattedDescription:u.formattedDescription,owner:u.channelOwner,downloadState:t.key},t];n.push(Y4(c,q[0],"mainVideoEntity"),Y4(c,q[1],"mainVideoDownloadStateEntity"))}return g.Rr.all(n)})}),0):b.return()})},i6=function(a,b){this.j=a;
this.U=b},t0a=function(a,b){var c,d,e,f,k,l;
return g.B(function(m){switch(m.j){case 1:return c=x5(b),d=g.IC(b.entityKey),e=d.entityId,g.ua(m,2),g.A(m,r0a(a,e),4);case 4:g.va(m,3);break;case 2:return f=g.wa(m),k="OFFLINE_OPERATION_FAILURE_REASON_UNKNOWN",f instanceof g.Ir&&"QUOTA_EXCEEDED"===f.type&&(k="OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"),m.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,k));case 3:var n;var p=null!=(n=b.actionMetadata)&&n.musicTrackEntityActionMetadata?{playbackDataActionMetadata:{maximumDownloadQuality:b.actionMetadata.musicTrackEntityActionMetadata.maximumDownloadQuality}}:
void 0;n=g.JC(e,"playbackData");p=Object.assign({},p,{priority:1,retryScheduleIntervalsInSeconds:s0a});l={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",entityKey:n,actionMetadata:p};return m.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c,[l]))}})},r0a=function(a,b){var c,d,e,f,k,l;
return g.B(function(m){switch(m.j){case 1:return g.A(m,d6([b]),2);case 2:return c=m.u,d=c[0],g.A(m,u0a(a,d),3);case 3:e=m.u;f=e.musicTrackEntity;k=e.musicArtistEntity;g.ua(m,4);var n=B5(f.thumbnailDetails),p=B5(k.thumbnailDetails);return g.A(m,w5(n.concat(p)),6);case 6:g.va(m,0);break;case 4:l=g.wa(m);if(!a.U.K("woffle_disable_thumbnails"))throw l;g.sa(m)}})},u0a=function(a,b){var c=void 0,d,e,f,k,l,m,n,p,q,t,u,x,y,z;
return g.B(function(D){if(1==D.j){if(!(b&&b.channel&&b.channel.offlineChannelData&&b.videoId&&b.additionalMetadatas))throw Error("Invalid OfflineVideoData");c||(c=Date.now().toString());e=g.r(b.additionalMetadatas);for(f=e.next();!f.done;f=e.next())k=f.value,k.offlineMusicVideoData&&(d=k.offlineMusicVideoData);if(!d)throw Error("Invalid OfflineMusicVideoData");m=null==(l=b.channel)?void 0:l.offlineChannelData;n={id:g.JC(b.videoId,"musicArtist"),externalChannelId:m.channelId,name:m.title,thumbnailDetails:m.thumbnail};
p={id:g.JC(b.videoId,"musicTrackDownloadMetadataEntity"),playbackData:g.JC(b.videoId,"playbackData"),addedTimestampMillis:c};z={id:g.JC(b.videoId,"musicTrack"),videoId:b.videoId,title:b.title,thumbnailDetails:b.thumbnail,lengthMs:String(1E3*Number(b.lengthSeconds)),albumTitle:null==(q=d)?void 0:q.releaseTitle,musicVideoType:null==(t=d)?void 0:t.musicVideoType,contentRating:{explicitType:null==(u=d)?void 0:u.explicitType},artists:[n.id],artistNames:(null==(x=d)?void 0:x.byline)||(null==(y=d)?void 0:
y.channelName),downloadMetadata:p.id};return g.A(D,d5(a.j,{mode:"readwrite",vc:!0},function(H){var J=Y4(H,n,"musicArtist"),L=Y4(H,p,"musicTrackDownloadMetadataEntity");H=Y4(H,z,"musicTrack");return g.Rr.all([J,L,H])}),2)}return D.return({musicTrackEntity:z,
musicArtistEntity:n})})},j6=function(){b6.apply(this,arguments);
this.I="musicTrack"},k6=function(){g.YI.apply(this,arguments)};
g.w(O3,N3);g.fa.Object.defineProperties(O3.prototype,{entityMetadata:{configurable:!0,enumerable:!0,get:function(){return this.j.entityMetadata},
set:function(a){this.j.entityMetadata=a}}});
g.w(P3,O3);P3.prototype.u=function(){return[]};
g.w(Q3,O3);Q3.prototype.u=function(){var a=[];this.j.alternateChannel&&a.push(this.j.alternateChannel);this.j.alternateChannelList&&a.push.apply(a,g.v(this.j.alternateChannelList));this.j.oneofChannelEntity&&a.push(this.j.oneofChannelEntity);return[].concat(g.v(new Set(a)))};
g.w(R3,O3);R3.prototype.u=function(){var a=[];this.j.entryCollection&&a.push(this.j.entryCollection);return[].concat(g.v(new Set(a)))};
g.w(S3,N3);S3.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);return[].concat(g.v(new Set(a)))};
g.w(T3,O3);T3.prototype.u=function(){var a=[];this.j.parentPlaylist&&a.push(this.j.parentPlaylist);if(this.j.entries)for(var b=g.r(this.j.entries),c=b.next();!c.done;c=b.next())a.push.apply(a,g.v((new S3(c.value)).u()));return[].concat(g.v(new Set(a)))};
g.w(U3,O3);U3.prototype.u=function(){var a=[];this.j.descriptionEntity&&a.push(this.j.descriptionEntity);this.j.creators&&a.push.apply(a,g.v(this.j.creators));this.j.theBiggestFan&&a.push(this.j.theBiggestFan);return[].concat(g.v(new Set(a)))};
g.w(V3,O3);V3.prototype.u=function(){return[]};
g.w(W3,O3);W3.prototype.u=function(){return[]};
g.w(X3,O3);X3.prototype.u=function(){return[]};
g.w(Y3,O3);Y3.prototype.u=function(){return[]};
g.w(Z3,O3);Z3.prototype.u=function(){return[]};
g.w($3,N3);$3.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playlist&&a.push(this.j.playlist);this.j.videoItem&&a.push(this.j.videoItem);return[].concat(g.v(new Set(a)))};
g.w(a4,O3);a4.prototype.u=function(){var a=[];this.j.refresh&&a.push(this.j.refresh);if(this.j.downloads)for(var b=g.r(this.j.downloads),c=b.next();!c.done;c=b.next())a.push.apply(a,g.v((new $3(c.value)).u()));return[].concat(g.v(new Set(a)))};
g.w(b4,O3);b4.prototype.u=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));return[].concat(g.v(new Set(a)))};
g.w(c4,O3);c4.prototype.u=function(){return[]};
g.w(d4,O3);d4.prototype.u=function(){var a=[];this.j.fakeChildren&&a.push.apply(a,g.v(this.j.fakeChildren));return[].concat(g.v(new Set(a)))};
g.w(e4,O3);e4.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.playbackData&&a.push(this.j.playbackData);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.v(new Set(a)))};
g.w(f4,O3);f4.prototype.u=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.videos&&a.push.apply(a,g.v(this.j.videos));this.j.collaboratorChannels&&a.push.apply(a,g.v(this.j.collaboratorChannels));return[].concat(g.v(new Set(a)))};
g.w(g4,O3);g4.prototype.u=function(){var a=[];this.j.video&&a.push(this.j.video);this.j.channelContributor&&a.push(this.j.channelContributor);return[].concat(g.v(new Set(a)))};
g.w(h4,N3);h4.prototype.u=function(){var a=[];this.j.playbackPosition&&a.push(this.j.playbackPosition);return[].concat(g.v(new Set(a)))};
g.w(i4,O3);i4.prototype.u=function(){var a=[];this.j.owner&&a.push(this.j.owner);this.j.downloadState&&a.push(this.j.downloadState);this.j.userState&&a.push.apply(a,g.v((new h4(this.j.userState)).u()));return[].concat(g.v(new Set(a)))};
g.w(j4,O3);j4.prototype.u=function(){return[]};
g.w(k4,O3);k4.prototype.u=function(){var a=[];this.j.channelOwner&&a.push(this.j.channelOwner);this.j.playbackPosition&&a.push(this.j.playbackPosition);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));this.j.downloadStatus&&a.push(this.j.downloadStatus);return[].concat(g.v(new Set(a)))};
g.w(l4,O3);l4.prototype.u=function(){return[]};
g.w(m4,O3);m4.prototype.u=function(){return[]};
g.w(n4,O3);n4.prototype.u=function(){return[]};
g.w(o4,O3);o4.prototype.u=function(){var a=[];this.j.trackDownloadMetadatas&&a.push.apply(a,g.v(this.j.trackDownloadMetadatas));return[].concat(g.v(new Set(a)))};
g.w(p4,O3);p4.prototype.u=function(){var a=[];this.j.playbackData&&a.push(this.j.playbackData);this.j.localImageEntities&&a.push.apply(a,g.v(this.j.localImageEntities));return[].concat(g.v(new Set(a)))};
g.w(q4,O3);q4.prototype.u=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.primaryArtists&&a.push.apply(a,g.v(this.j.primaryArtists));this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);this.j.tracks&&a.push.apply(a,g.v(this.j.tracks));this.j.share&&a.push(this.j.share);this.j.downloadMetadata&&a.push(this.j.downloadMetadata);return[].concat(g.v(new Set(a)))};
g.w(r4,O3);r4.prototype.u=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);this.j.tracks&&a.push.apply(a,g.v(this.j.tracks));return[].concat(g.v(new Set(a)))};
g.w(s4,O3);s4.prototype.u=function(){var a=[];this.j.albumRelease&&a.push(this.j.albumRelease);return[].concat(g.v(new Set(a)))};
g.w(t4,O3);t4.prototype.u=function(){var a=[];this.j.details&&a.push(this.j.details);this.j.userDetails&&a.push(this.j.userDetails);return[].concat(g.v(new Set(a)))};
g.w(u4,O3);u4.prototype.u=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.v(new Set(a)))};
g.w(v4,O3);v4.prototype.u=function(){var a=[];this.j.parentArtist&&a.push(this.j.parentArtist);return[].concat(g.v(new Set(a)))};
g.w(w4,O3);w4.prototype.u=function(){return[]};
g.w(x4,O3);x4.prototype.u=function(){return[]};
g.w(y4,O3);y4.prototype.u=function(){return[]};
g.w(z4,O3);
z4.prototype.u=function(){var a=[];this.j.musicLibraryStatusEntity&&a.push(this.j.musicLibraryStatusEntity);this.j.artists&&a.push.apply(a,g.v(this.j.artists));this.j.audioModeVersion&&a.push(this.j.audioModeVersion);this.j.videoModeVersion&&a.push(this.j.videoModeVersion);this.j.userDetails&&a.push(this.j.userDetails);this.j.details&&a.push(this.j.details);this.j.albumRelease&&a.push(this.j.albumRelease);this.j.share&&a.push(this.j.share);this.j.libraryEdit&&a.push(this.j.libraryEdit);this.j.downloadMetadata&&
a.push(this.j.downloadMetadata);return[].concat(g.v(new Set(a)))};
g.w(A4,O3);A4.prototype.u=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.v(new Set(a)))};
g.w(B4,O3);B4.prototype.u=function(){var a=[];this.j.parentTrack&&a.push(this.j.parentTrack);return[].concat(g.v(new Set(a)))};
g.w(C4,O3);C4.prototype.u=function(){return[]};
g.w(D4,O3);D4.prototype.u=function(){return[]};
g.w(E4,O3);E4.prototype.u=function(){return[]};
g.w(F4,O3);F4.prototype.u=function(){return[]};
g.w(G4,O3);G4.prototype.u=function(){var a=[];this.j.transfer&&a.push(this.j.transfer);this.j.adsPlaybackData&&a.push.apply(a,g.v(this.j.adsPlaybackData));this.j.drmLicense&&a.push(this.j.drmLicense);this.j.offlineVideoPolicy&&a.push(this.j.offlineVideoPolicy);return[].concat(g.v(new Set(a)))};
g.w(H4,O3);H4.prototype.u=function(){return[]};
g.w(I4,O3);I4.prototype.u=function(){var a=[];this.j.offlineVideoStreams&&a.push.apply(a,g.v(this.j.offlineVideoStreams));this.j.captionTrack&&a.push.apply(a,g.v(this.j.captionTrack));return[].concat(g.v(new Set(a)))};
g.w(J4,O3);J4.prototype.u=function(){return[]};
g.w(K4,O3);K4.prototype.u=function(){return[]};
g.w(L4,O3);L4.prototype.u=function(){return[]};
g.w(M4,O3);M4.prototype.u=function(){return[]};
g.w(N4,O3);N4.prototype.u=function(){return[]};
var T_a=["offline"],PZa=["offline/get_playback_data_entity"],P4;g.w(Q4,g.Dr);g.w(S4,NYa);S4.prototype.B=function(a,b){b=R4(b);a=(new TextEncoder).encode(JSON.stringify(a));return this.j.encrypt(a,b)};
S4.prototype.u=function(a,b){if(!(a instanceof Uint8Array))throw JYa(1);var c=new TextDecoder;b=R4(b);a=this.j.decrypt(a,b);return JSON.parse(c.decode(a))};
var PYa={buttonEntity:J4,captionTrack:C4,channelHandle:P3,commerceCartListEntity:L4,downloadQualityPickerEntity:Y3,downloadsPageRefreshTokenEntity:Z3,downloadsPageViewConfigurationEntity:l4,fakeChannel:Q3,fakePlaylist:R3,fakePlaylistEntryCollection:T3,fakeVideo:U3,fakeVideoDescription:V3,iconBadgeEntity:M4,liveChatPollStateEntity:X3,logoEntity:W3,mainDownloadsListEntity:a4,mainPlaylistEntity:f4,mainPlaylistVideoEntity:g4,mainVideoDownloadStateEntity:b4,mainVideoEntity:i4,markersVisibilityOverrideEntity:m4,
musicAlbumReleaseDetail:r4,musicAlbumReleaseDownloadMetadataEntity:o4,musicAlbumRelease:q4,musicAlbumReleaseUserDetail:s4,musicArtistDetail:u4,musicArtist:t4,musicArtistUserDetail:v4,musicLibraryEdit:w4,musicLibraryStatusEntity:x4,musicShare:y4,musicTrackDetail:A4,musicTrackDownloadMetadataEntity:p4,musicTrack:z4,musicTrackUserDetail:B4,offlineOrchestrationActionWrapperEntity:D4,offlineVideoPolicy:E4,offlineVideoStreams:F4,offlineabilityEntity:c4,orchestrationWebSamplingEntity:d4,pinnedProductEntity:n4,
playbackData:G4,quantityIncrementerEntity:N4,refresh:H4,transfer:I4,videoPlaybackPositionEntity:K4,ytMainChannelEntity:j4,ytMainDownloadedVideoEntity:e4,ytMainVideoEntity:k4};g.w(b5,NYa);b5.prototype.B=function(a){return a};
b5.prototype.u=function(a){if(a instanceof Uint8Array)throw JYa(0);return a};
g.w(c5,g.G);c5.prototype.B=function(a){ZYa(this,a.data)};
c5.prototype.ea=function(){this.channel.close()};
var i5,v0a={H3:"captionTrack",p7:"ytMainDownloadedVideoEntity",q7:"ytMainVideoEntity",haa:"ytMainChannelEntity",iaa:"mainPlaylistEntity",jaa:"mainPlaylistVideoEntity",maa:"mainVideoEntity",naa:"mainVideoDownloadStateEntity",uca:"musicAlbumReleaseDetail",vca:"musicAlbumReleaseDownloadMetadataEntity",wca:"musicAlbumRelease",xca:"musicAlbumReleaseUserDetail",yca:"musicArtistDetail",zca:"musicArtist",Bca:"musicArtistUserDetail",Kca:"musicLibraryEdit",Lca:"musicLibraryStatusEntity",Vca:"musicShare",bda:"musicTrackDetail",
cda:"musicTrackDownloadMetadataEntity",dda:"musicTrack",eda:"musicTrackUserDetail",uda:"offlineOrchestrationActionWrapperEntity",Eda:"offlineVideoPolicy",Fda:"offlineVideoStreams",rea:"playbackData",tfa:"orchestrationWebSamplingEntity",Bga:"downloadsPageViewConfigurationEntity",Cga:"refresh",Dga:"mainDownloadsListEntity",Ega:"downloadsPageRefreshTokenEntity",mha:"transfer"};g.w(l5,g.G);l5.prototype.B=function(a){this.api.Ma("onOfflineOperationFailure",a.data)};
l5.prototype.C=function(a){this.api.X("offlinetransferpause",a.data)};
l5.prototype.ea=function(){var a;null==(a=this.j)||a.close();var b;null==(b=this.u)||b.close()};qZa.prototype.request=function(a,b,c){b=void 0===b?{}:b;return this.locks.request(a,b,function(d){return c(d)})};tZa.prototype.wf=function(){this.j&&n5(this)};var t5=g.C.caches,s5,u5;p5.prototype.open=function(a){return t5.open(r5(a))};
p5.prototype.has=function(a){return t5.has(r5(a))};
p5.prototype.delete=function(a){return t5.delete(r5(a))};
p5.prototype.match=function(a,b){var c=this,d,e,f,k,l,m;return g.B(function(n){switch(n.j){case 1:return g.A(n,c.keys(),2);case 2:d=n.u,e=g.r(d),f=e.next();case 3:if(f.done){n.Ra(5);break}k=f.value;return g.A(n,c.open(k),6);case 6:return l=n.u,g.A(n,l.match(a,b),7);case 7:if(m=n.u)return n.return(m);f=e.next();n.Ra(3);break;case 5:return n.return()}})};
g.w(q5,p5);q5.prototype.keys=function(){var a,b,c,d,e,f,k,l,m;return g.B(function(n){if(1==n.j)return a=[],b=g.Er("CacheStorage keys"),g.A(n,t5.keys(),2);c=n.u;d=g.r(c);for(e=d.next();!e.done;e=d.next()){f=e.value;var p=f.indexOf(":");k=-1===p?{OC:f}:{OC:f.substring(0,p),datasyncId:f.substring(p+1)};l=k.OC;m=k.datasyncId;m===b&&a.push(l)}return n.return(a)})};Object.keys(v0a).map(function(a){return v0a[a]});
var JZa="captionTrack ytMainDownloadedVideoEntity ytMainVideoEntity ytMainChannelEntity mainPlaylistEntity mainVideoEntity mainVideoDownloadStateEntity offlineVideoPolicy offlineVideoStreams playbackData transfer".split(" ");g.w(H5,F5);H5.prototype.u=function(a){return y5(a)?NZa(this,a):z5(a)?OZa(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};g.w(J5,F5);J5.prototype.u=function(a){return y5(a)?RZa(this,a):z5(a)?SZa(this,a):"OFFLINE_ORCHESTRATION_ACTION_TYPE_UPDATE"===a.actionType&&a.entityKey?this.handleUpdate(a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
J5.prototype.handleUpdate=function(a){var b=this,c,d,e;return g.B(function(f){switch(f.j){case 1:return c=x5(a),g.A(f,g5(b.j,a.entityKey,"transfer"),2);case 2:d=f.u;if(!d||"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"!==d.transferState)return f.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c));g.ua(f,3);d.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE";return g.A(f,f5(b.j,d,"transfer"),5);case 5:e=g.IC(d.key).entityId;o5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_PLAYER_RESPONSE_REFRESH",
statusType:"ADDED_TO_QUEUE"},{videoId:e,jj:d});g.va(f,4);break;case 3:return g.wa(f),f.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_FAILURE",c,void 0,"OFFLINE_OPERATION_FAILURE_REASON_DATABASE_REQUEST_FAILED"));case 4:return f.return(new G5("OFFLINE_ORCHESTRATION_ACTION_RESULT_SUCCESS",c))}})};var h_a=["OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD","OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH"];var M5;$Za.prototype.j=function(a,b){var c=a.action.actionMetadata.priority-b.action.actionMetadata.priority;0===c&&(a.j<b.j?c=-1:a.j>b.j&&(c=1));return c};g.w(P5,g.G);P5.prototype.ea=function(){this.J&&this.J();g.G.prototype.ea.call(this)};
P5.prototype.createAction=function(a,b){var c=g.IC(a.entityKey).entityType,d=g.Ku(16);return new K5(c,d,a,b.actionId,b.rootActionId)};
P5.prototype.W=function(a){var b=this,c,d,e,f,k,l,m,n,p;return g.B(function(q){if(1==q.j){if(b.isDisposed())return q.return();d=null!=(c=a.offlineOrchestrationActionWrapperEntity)?c:new Set;e=[];f=g.r(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.IC(l),n=m.entityId,b_a(b.j,n)||e.push(l);return g.A(q,j_a(b,e),2)}p=q.u;return g.A(q,R5(b,p),0)})};
P5.prototype.retry=function(){var a=this;return g.B(function(b){return g.A(b,k_a(a),0)})};g.h=q_a.prototype;
g.h.aZ=function(a){var b=this,c,d,e,f;return g.B(function(k){if(!g.U(a.state,128))return k.Ra(0);var l=null==(c=a.state.getData())?void 0:c.errorCode,m=null==(d=a.state.getData())?void 0:d.OI,n=null==(e=a.state.getData())?void 0:e.oB;f=b.K("html5_eliminate_net_retryexhausted_error")&&"net.connect"===l&&1===n||"net.retryexhausted"===l&&(null==m?0:m.includes("net.connect"))?"TRANSFER_FAILURE_REASON_NETWORK_LOST":(null==l?0:l.startsWith("net."))?"TRANSFER_FAILURE_REASON_NETWORK":"TRANSFER_FAILURE_REASON_INTERNAL";return g.A(k,
b.xs(b.player.getVideoData().videoId,f),0)})};
g.h.xs=function(a,b){var c=this;return g.B(function(d){if(1==d.j){if(c.u)return d.return();c.u=!0;return"TRANSFER_FAILURE_REASON_NETWORK_LOST"===b?(T5(c,a,!1,!0),d.Ra(0)):g.A(d,S5(c,a),3)}g.VC(a,4);return g.A(d,c.j.xs(b),0)})};
g.h.GC=function(a){2===a.status?(a.status!==this.B&&(Y5(this.j),g.VC(a.videoId,2)),a.nz&&L_a(this.j,a.videoId,a.nz)):4===a.status?(S5(this,a.videoId),this.xs(a.videoId,a.WB?"TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":"TRANSFER_FAILURE_REASON_INTERNAL")):1===a.status&&J_a(this.j);this.B=a.status;this.api.Ma("localmediachange",{videoId:a.videoId,status:a.status})};
g.h.mI=function(){var a=this,b;return g.B(function(c){if(1==c.j){if(a.u)return c.return();a.u=!0;b=a.player.getVideoData().videoId;return g.A(c,S5(a,b),2)}return g.A(c,a.j.mI(),0)})};
g.h.K=function(a){return this.api.S().K(a)};g.w(U5,g.G);U5.prototype.ea=function(){this.u&&this.u();g.G.prototype.ea.call(this)};
U5.prototype.B=function(a){var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){d=null!=(c=a.transfer)?c:new Set;e=[];f=g.r(d);for(k=f.next();!k.done;k=f.next())l=k.value,m=g.IC(l),n=m.entityId,e.push(n);return 0===e.length?p.return():g.A(p,x_a(b,e),0)})};g.w(V5,g.G);g.h=V5.prototype;g.h.ea=function(){this.J&&this.J();this.N.dispose();this.C.dispose();this.Y&&g.ef(this.D.B,this.Y);this.W&&g.ef(this.D.B,this.W);g.G.prototype.ea.call(this)};
g.h.l0=function(a){var b=this,c,d;return g.B(function(e){if(1==e.j)return c=g.JC(a,"transfer"),b.j&&c===b.j.key?(T5(b.I,b.B,!0),b.C.stop(),e.Ra(0)):g.A(e,d5(b.u,{mode:"readwrite",vc:!0},function(f){return V4(f,c,"transfer").then(function(k){if(k&&"TRANSFER_STATE_COMPLETE"!==k.transferState&&"TRANSFER_STATE_FAILED"!==k.transferState)return k.transferState="TRANSFER_STATE_PAUSED_BY_USER",Y4(f,k,"transfer").then(function(){return k})})}),3);
(d=e.u)&&zZa({videoId:a,jj:d});g.sa(e)})};
g.h.k0=function(){this.j&&this.B&&T5(this.I,this.B,!1);this.C.stop()};
g.h.Az=function(){this.j?D_a(this,this.j):X5(this)};
g.h.SS=function(a){var b=this,c;return g.B(function(d){switch(d.j){case 1:if(!b.j){d.Ra(2);break}if("TRANSFER_STATE_COMPLETE"===b.j.transferState||"TRANSFER_STATE_FAILED"===b.j.transferState||!a.transfer||!a.transfer.has(b.j.key)){d.Ra(3);break}c=b;return g.A(d,g5(b.u,b.j.key,"transfer"),4);case 4:c.j=d.u;if(b.j){d.Ra(3);break}return g.A(d,E_a(b),3);case 3:if(b.j)return d.return();case 2:return g.A(d,X5(b),0)}})};
g.h.xs=function(a,b){var c=this,d,e;return g.B(function(f){if(1==f.j){a:switch(a){case "TRANSFER_FAILURE_REASON_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_EXTERNAL_FILESYSTEM_WRITE":case "TRANSFER_FAILURE_REASON_PLAYABILITY":case "TRANSFER_FAILURE_REASON_TOO_MANY_RETRIES":var k=!1;break a;default:k=!0}return k&&M_a(c)?g.A(f,$5(c,"TRANSFER_STATE_TRANSFER_IN_QUEUE"),5):g.A(f,N_a(c,a),3)}3!=f.j&&(d=g.IC(c.j.key).entityId,o5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_RETRY",statusType:"ADDED_TO_QUEUE"},
{videoId:d,jj:c.j}));W5(c);e=X5(c,!0);b&&b(e);g.sa(f)})};
g.h.mI=function(a){var b=this,c,d,e,f,k,l;return g.B(function(m){if(1==m.j)return M_a(b)?g.A(m,$5(b,"TRANSFER_STATE_WAITING_FOR_PLAYER_RESPONSE_REFRESH"),5):g.A(m,N_a(b,"TRANSFER_FAILURE_REASON_STREAM_MISSING"),3);if(3!=m.j)return c=g.IC(b.j.key).entityId,o5({transferStatusType:"TRANSFER_STATUS_TYPE_DEQUEUED_BY_PLAYER_RESPONSE_EXPIRATION",statusType:"ADDED_TO_QUEUE"},{videoId:c,jj:b.j}),d=UZa(),d.playbackDataActionMetadata={isEnqueuedForExpiredStreamUrlRefetch:!0},e=g.JC(c,"playbackData"),f={actionType:"OFFLINE_ORCHESTRATION_ACTION_TYPE_ADD",
entityKey:e,actionMetadata:d},k=L5(new K5("playbackData",c,f)),g.A(m,f5(b.u,k,"offlineOrchestrationActionWrapperEntity"),3);W5(b);l=X5(b,!0);a&&a(l);g.sa(m)})};
var l6={},a6=(l6.TRANSFER_STATE_TRANSFERRING=1,l6.TRANSFER_STATE_TRANSFER_IN_QUEUE=2,l6);g.h=b6.prototype;g.h.Sx=function(a){var b={};return b.playbackData=new H5(a,this.U,this.u),b.transfer=new J5(a),b};
g.h.eJ=function(){var a=this;return g.B(function(b){return a.j?g.A(b,B_a(a.j),0):b.Ra(0)})};
g.h.isOrchestrationLeader=function(){return this.B.j};
g.h.BI=function(a){var b=this.u;b.api.X("offlinetransferpause",a);var c;null==(c=b.u)||c.postMessage(a)};
g.h.Az=function(a){var b,c;return g.B(function(d){if(1==d.j)return g.A(d,j5(),2);b=d.u;if(!b)return d.return();c=g.JC(a,"transfer");return g.A(d,d5(b,{mode:"readwrite",vc:!0},function(e){return V4(e,c,"transfer").then(function(f){return f&&"TRANSFER_STATE_PAUSED_BY_USER"===f.transferState?(f.transferState="TRANSFER_STATE_TRANSFER_IN_QUEUE",Y4(e,f,"transfer").then(function(){o5({transferStatusType:"TRANSFER_STATUS_TYPE_REENQUEUED_BY_USER_RESUME",statusType:"USER_RESUMED"},{videoId:a,jj:f});return g.Rr.resolve(null)})):
g.Rr.resolve(null)})}),0)})};
g.h.wz=function(a){a=void 0===a?43200:a;var b=this,c,d,e,f,k,l,m,n;return g.B(function(p){if(1==p.j)return b.N.vf()?g.A(p,j5(),2):p.return(S_a());if(3!=p.j){c=p.u;if(!c)return p.return([]);d=Date.now()/1E3;return g.A(p,h5(c,"offlineVideoPolicy"),3)}e=p.u;f=[];k=g.r(e);for(l=k.next();!l.done;l=k.next())m=l.value,Number(m.lastUpdatedTimestampSeconds)+a<=d&&(n=g.IC(m.key).entityId,f.push(n));return f.length?p.return(c6(b,f,b.I,"OFFLINE_ORCHESTRATION_ACTION_TYPE_REFRESH")):p.return([])})};
g.h.deleteAll=function(){return c6(this,["!*$_ALL_ENTITIES_!*$"],this.I,"OFFLINE_ORCHESTRATION_ACTION_TYPE_DELETE")};g.w(e6,F5);e6.prototype.u=function(a){return y5(a)?X_a(this,a):A5(a)?Y_a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var W_a=[10];g.w(f6,F5);f6.prototype.u=function(a){return y5(a)?e0a(this,a):z5(a)?f0a(this,a):A5(a)?g0a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var i0a=[10];g.w(g6,F5);g6.prototype.u=function(a){return y5(a)?l0a(this,a):z5(a)?m0a(this,a):A5(a)?n0a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var p0a=[10];g.w(h6,b6);h6.prototype.Sx=function(a){var b=b6.prototype.Sx.call(this,a);b.ytMainDownloadedVideoEntity=new g6(a,this.U,this.u);b.mainVideoEntity=new f6(a,this.U,this.u);b.mainPlaylistEntity=new e6(a,this.U,this.u);return b};
h6.prototype.eJ=function(){var a=this;return g.B(function(b){return 1==b.j?g.A(b,b6.prototype.eJ.call(a),2):a.U.K("woffle_entity_migration")?g.A(b,q0a(),0):b.Ra(0)})};g.w(i6,F5);i6.prototype.u=function(a){return y5(a)?t0a(this,a):Promise.reject(Error("Unsupported action type: "+a.actionType))};
var s0a=[10];g.w(j6,b6);j6.prototype.Sx=function(a){var b=b6.prototype.Sx.call(this,a);b.musicTrack=new i6(a,this.U);return b};g.w(k6,g.YI);g.h=k6.prototype;g.h.create=function(){var a=this.player.S();g.VB(a)?this.j=new h6(a,this.player):g.jB(a)&&(this.j=new j6(a,this.player))};
g.h.ej=function(){return!1};
g.h.QI=function(a,b,c,d){var e=this;return g.B(function(f){return e.j?f.return(c6(e.j,a,b,c,d)):f.return(Promise.reject())})};
g.h.deleteAll=function(){return this.j.deleteAll()};
g.h.wz=function(a){return this.j.wz(a)};
g.h.BI=function(a){this.j.BI(a)};
g.h.Az=function(a){return this.j.Az(a)};
g.h.isOrchestrationLeader=function(){return this.j.isOrchestrationLeader()};g.XI("offline",k6);})(_yt_player);
